/* ===== 硬核英语社 · 课程数据 =====
 * 说明：句子/单词为教学示例，句子用于「看中文敲英文」「拼句闯关」，
 *       单词用于「单词闯关」。句子统一使用完整形式（do not / I am），
 *       便于打字练习时精确比对。
 */
const COURSES = [
  {
    id: "basics", title: "零基础学英语（动物·星期·水果）", cat: "零基础",
    emoji: "🐱", cover: "green", learners: 7600, level: "入门",
    desc: "从字母和基础句型起步，认识动物、星期、水果等最常用表达。",
    words: [
      { en: "cat", zh: "猫" }, { en: "Wednesday", zh: "星期三" }, { en: "apple", zh: "苹果" },
      { en: "dog", zh: "狗" }, { en: "banana", zh: "香蕉" }, { en: "book", zh: "书" },
    ],
    lessons: [
      { zh: "我是一只猫。", en: "I am a cat." },
      { zh: "今天星期三。", en: "Today is Wednesday." },
      { zh: "她喜欢苹果。", en: "She likes apples." },
      { zh: "那是一只狗。", en: "That is a dog." },
      { zh: "我们吃香蕉。", en: "We eat bananas." },
      { zh: "这是我的书。", en: "This is my book." },
      { zh: "他有一只鸟。", en: "He has a bird." },
      { zh: "我喜欢星期一。", en: "I like Monday." },
    ],
  },
  {
    id: "grammar", title: "语法渐进式突破", cat: "零基础",
    emoji: "🧩", cover: "green", learners: 7532, level: "初级",
    desc: "用最直白的例句讲清时态、句型与主谓宾，搭好语法骨架。",
    words: [
      { en: "teacher", zh: "老师" }, { en: "running", zh: "跑步" }, { en: "interesting", zh: "有趣的" },
      { en: "homework", zh: "作业" }, { en: "taller", zh: "更高的" }, { en: "yesterday", zh: "昨天" },
    ],
    lessons: [
      { zh: "她是一个老师。", en: "She is a teacher." },
      { zh: "他们正在跑步。", en: "They are running." },
      { zh: "我昨天看了电影。", en: "I watched a movie yesterday." },
      { zh: "这本书很有趣。", en: "This book is interesting." },
      { zh: "如果下雨我们就待在家。", en: "If it rains we will stay at home." },
      { zh: "我已经完成了作业。", en: "I have finished my homework." },
      { zh: "她比我高。", en: "She is taller than me." },
      { zh: "这是我昨天买的书。", en: "This is the book I bought yesterday." },
    ],
  },
  {
    id: "nc1", title: "新概念英语 第1册", cat: "教材同步",
    emoji: "📘", cover: "blue", learners: 3855, level: "初级",
    desc: "经典新概念第一册，短句打磨听说基础。",
    words: [
      { en: "umbrella", zh: "雨伞" }, { en: "London", zh: "伦敦" }, { en: "tea", zh: "茶" },
      { en: "name", zh: "名字" }, { en: "fine", zh: "好的" }, { en: "goodbye", zh: "再见" },
    ],
    lessons: [
      { zh: "很高兴见到你。", en: "Nice to meet you." },
      { zh: "这是你的伞吗？", en: "Is this your umbrella?" },
      { zh: "他正在看书。", en: "He is reading a book." },
      { zh: "请给我一杯茶。", en: "Please give me a cup of tea." },
      { zh: "他们明天去伦敦。", en: "They will go to London tomorrow." },
      { zh: "你叫什么名字？", en: "What is your name?" },
      { zh: "我很好，谢谢。", en: "I am fine, thank you." },
      { zh: "再见，明天见。", en: "Goodbye, see you tomorrow." },
    ],
  },
  {
    id: "nc2", title: "新概念英语 第2册", cat: "教材同步",
    emoji: "📗", cover: "blue", learners: 3640, level: "中级",
    desc: "新概念第二册，复合句与叙事表达进阶。",
    words: [
      { en: "neighbor", zh: "邻居" }, { en: "airport", zh: "机场" }, { en: "suddenly", zh: "突然" },
      { en: "never", zh: "从未" }, { en: "journey", zh: "旅程" }, { en: "quiet", zh: "安静的" },
    ],
    lessons: [
      { zh: "我的邻居是个飞行员。", en: "My neighbor is a pilot." },
      { zh: "他昨天到达了北京。", en: "He arrived in Beijing yesterday." },
      { zh: "请把窗户关上。", en: "Please close the window." },
      { zh: "她正在花园里工作。", en: "She is working in the garden." },
      { zh: "我们度过了一个美妙的夜晚。", en: "We had a wonderful evening." },
      { zh: "我从未去过那里。", en: "I have never been there." },
      { zh: "他说明天会下雨。", en: "He said it would rain tomorrow." },
      { zh: "如果我有时间就去。", en: "If I have time, I will go." },
    ],
  },
  {
    id: "nc3", title: "新概念英语 第3册", cat: "教材同步",
    emoji: "📙", cover: "blue", learners: 3402, level: "高级",
    desc: "新概念第三册，长难句与地道表达。",
    words: [
      { en: "disaster", zh: "灾难" }, { en: "ancient", zh: "古老的" }, { en: "silence", zh: "寂静" },
      { en: "doubt", zh: "怀疑" }, { en: "succeed", zh: "成功" }, { en: "action", zh: "行动" },
    ],
    lessons: [
      { zh: "事故的原因尚未查明。", en: "The cause of the accident remains unknown." },
      { zh: "这座古城有悠久的历史。", en: "The ancient city has a long history." },
      { zh: "他保持着沉默。", en: "He remained in silence." },
      { zh: "我们应该从中吸取教训。", en: "We should learn a lesson from it." },
      { zh: "天气影响了我们的计划。", en: "The weather affected our plan." },
      { zh: "毫无疑问，他会成功。", en: "There is no doubt that he will succeed." },
      { zh: "这个决定影响深远。", en: "This decision has far-reaching effects." },
      { zh: "我们必须立刻采取行动。", en: "We must take action immediately." },
    ],
  },
  {
    id: "primary", title: "小学英语同步·三年级上", cat: "教材同步",
    emoji: "🎒", cover: "blue", learners: 4100, level: "入门",
    desc: "贴合小学三年级上册进度，课内同步练句型。",
    words: [
      { en: "school", zh: "学校" }, { en: "red", zh: "红色" }, { en: "friend", zh: "朋友" },
      { en: "pencil", zh: "铅笔" }, { en: "sing", zh: "唱歌" }, { en: "happy", zh: "开心的" },
    ],
    lessons: [
      { zh: "这是我的学校。", en: "This is my school." },
      { zh: "我喜欢红色。", en: "I like red." },
      { zh: "他是我的好朋友。", en: "He is my good friend." },
      { zh: "我们有一只猫。", en: "We have a cat." },
      { zh: "早上好，老师。", en: "Good morning, teacher." },
      { zh: "这是我的铅笔。", en: "This is my pencil." },
      { zh: "我会唱歌。", en: "I can sing." },
      { zh: "你几岁了？", en: "How old are you?" },
    ],
  },
  {
    id: "daily900", title: "日常口语高频句", cat: "日常口语",
    emoji: "💬", cover: "orange", learners: 4040, level: "初级",
    desc: "覆盖生活高频场景，日常表达随练随用。",
    words: [
      { en: "restaurant", zh: "餐厅" }, { en: "help", zh: "帮助" }, { en: "time", zh: "时间" },
      { en: "understand", zh: "理解" }, { en: "moment", zh: "片刻" }, { en: "welcome", zh: "受欢迎的" },
      { en: "problem", zh: "问题" }, { en: "again", zh: "再一次" },
    ],
    lessons: [
      { zh: "你能帮我一下吗？", en: "Can you help me please?" },
      { zh: "我在学英语。", en: "I am learning English." },
      { zh: "这家餐厅很好吃。", en: "This restaurant is very good." },
      { zh: "我们走吧。", en: "Let us go." },
      { zh: "现在几点了？", en: "What time is it now?" },
      { zh: "打扰一下。", en: "Excuse me." },
      { zh: "抱歉，我迟到了。", en: "Sorry, I am late." },
      { zh: "我不太明白。", en: "I do not understand." },
      { zh: "能再说一遍吗？", en: "Could you say that again?" },
      { zh: "请稍等一下。", en: "Please wait a moment." },
      { zh: "我同意。", en: "I agree." },
      { zh: "我不这么认为。", en: "I do not think so." },
      { zh: "没问题。", en: "No problem." },
      { zh: "非常感谢你的帮助。", en: "Thank you so much for your help." },
      { zh: "不用谢。", en: "You are welcome." },
      { zh: "我需要一些帮助。", en: "I need some help." },
      { zh: "我很喜欢这里。", en: "I really like it here." },
      { zh: "一会儿见。", en: "See you later." },
    ],
  },
  {
    id: "travel", title: "旅游英语口语", cat: "日常口语",
    emoji: "✈️", cover: "purple", learners: 2240, level: "初级",
    desc: "出国旅行必备口语，机场、问路、购物全搞定。",
    words: [
      { en: "airport", zh: "机场" }, { en: "ticket", zh: "票" }, { en: "restroom", zh: "洗手间" },
      { en: "flight", zh: "航班" }, { en: "gate", zh: "登机口" }, { en: "luggage", zh: "行李" },
      { en: "hotel", zh: "酒店" }, { en: "breakfast", zh: "早餐" }, { en: "subway", zh: "地铁" },
      { en: "discount", zh: "折扣" },
    ],
    lessons: [
      { zh: "我要去机场。", en: "I want to go to the airport." },
      { zh: "一张去北京的票。", en: "One ticket to Beijing." },
      { zh: "厕所在哪里？", en: "Where is the restroom?" },
      { zh: "这个多少钱？", en: "How much is this?" },
      { zh: "请帮我拍照。", en: "Please take a photo for me." },
      { zh: "我的航班几点起飞？", en: "What time does my flight leave?" },
      { zh: "登机口在哪里？", en: "Where is the boarding gate?" },
      { zh: "我想要靠窗的座位。", en: "I would like a window seat." },
      { zh: "这趟航班晚点了吗？", en: "Is this flight delayed?" },
      { zh: "我预订了一间房。", en: "I booked a room." },
      { zh: "房费含早餐吗？", en: "Is breakfast included?" },
      { zh: "有免费无线网络吗？", en: "Is there free wifi?" },
      { zh: "附近有超市吗？", en: "Is there a supermarket nearby?" },
      { zh: "到市中心怎么走？", en: "How do I get to the city center?" },
      { zh: "可以刷信用卡吗？", en: "Can I pay by credit card?" },
      { zh: "太贵了，能便宜点吗？", en: "It is too expensive, can you give me a discount?" },
      { zh: "我要买这个。", en: "I will take this one." },
      { zh: "请问地铁站在哪里？", en: "Where is the subway station please?" },
      { zh: "这里可以退税吗？", en: "Can I get a tax refund here?" },
      { zh: "我迷路了，能帮帮我吗？", en: "I am lost, can you help me?" },
    ],
  },
  {
    id: "food", title: "餐饮英语口语", cat: "日常口语",
    emoji: "🍜", cover: "orange", learners: 2560, level: "初级",
    desc: "点餐、评价、买单，餐桌英语不冷场。",
    words: [
      { en: "menu", zh: "菜单" }, { en: "delicious", zh: "美味的" }, { en: "bill", zh: "账单" },
      { en: "table", zh: "餐桌" }, { en: "spicy", zh: "辣的" }, { en: "salty", zh: "咸的" },
      { en: "coffee", zh: "咖啡" }, { en: "recommend", zh: "推荐" },
    ],
    lessons: [
      { zh: "请给我菜单。", en: "Please give me the menu." },
      { zh: "这道菜很好吃。", en: "This dish is delicious." },
      { zh: "我想买单。", en: "I would like the bill." },
      { zh: "你们有什么推荐？", en: "What do you recommend?" },
      { zh: "我要一杯咖啡。", en: "I would like a cup of coffee." },
      { zh: "我想预订一张两人桌。", en: "I would like to reserve a table for two." },
      { zh: "还有空位吗？", en: "Do you have a table available?" },
      { zh: "我对花生过敏。", en: "I am allergic to peanuts." },
      { zh: "请不要做得太辣。", en: "Please do not make it too spicy." },
      { zh: "请不要加糖。", en: "Please do not add sugar." },
      { zh: "可以打包吗？", en: "Can I get this to go?" },
      { zh: "这道菜太咸了。", en: "This dish is too salty." },
      { zh: "服务很好，谢谢。", en: "The service was great, thank you." },
      { zh: "可以分开结账吗？", en: "Can we have separate bills?" },
    ],
  },
  {
    id: "health", title: "健康生活英语", cat: "日常口语",
    emoji: "💪", cover: "orange", learners: 1980, level: "初级",
    desc: "看医生、健身、作息，健康话题随身练。",
    words: [
      { en: "doctor", zh: "医生" }, { en: "exercise", zh: "锻炼" }, { en: "healthy", zh: "健康的" },
      { en: "headache", zh: "头痛" }, { en: "medicine", zh: "药" }, { en: "stress", zh: "压力" },
      { en: "water", zh: "水" }, { en: "sleep", zh: "睡觉" },
    ],
    lessons: [
      { zh: "我需要看医生。", en: "I need to see a doctor." },
      { zh: "每天锻炼很重要。", en: "Daily exercise is important." },
      { zh: "保持健康的饮食。", en: "Keep a healthy diet." },
      { zh: "我感冒了。", en: "I have a cold." },
      { zh: "早点睡觉。", en: "Go to bed early." },
      { zh: "我头疼。", en: "I have a headache." },
      { zh: "我需要吃药。", en: "I need to take medicine." },
      { zh: "我对这种药过敏。", en: "I am allergic to this medication." },
      { zh: "我每天跑步半小时。", en: "I run for half an hour every day." },
      { zh: "多喝水对身体好。", en: "Drinking more water is good for you." },
      { zh: "我最近压力很大。", en: "I have been under a lot of stress lately." },
      { zh: "请深呼吸，放松一下。", en: "Please take a deep breath and relax." },
    ],
  },
  {
    id: "cet", title: "四六级核心句子", cat: "考试备考",
    emoji: "🎓", cover: "purple", learners: 3120, level: "中级",
    desc: "四六级高频写作句型，背熟就能用。",
    words: [
      { en: "education", zh: "教育" }, { en: "environment", zh: "环境" }, { en: "technology", zh: "科技" },
      { en: "internet", zh: "互联网" }, { en: "communication", zh: "沟通" }, { en: "teamwork", zh: "团队合作" },
      { en: "efficiency", zh: "效率" }, { en: "failure", zh: "失败" },
    ],
    lessons: [
      { zh: "教育对个人发展至关重要。", en: "Education is vital to personal development." },
      { zh: "我们应当保护环境。", en: "We should protect the environment." },
      { zh: "科技改变了我们的生活方式。", en: "Technology has changed our way of life." },
      { zh: "健康比财富更重要。", en: "Health is more important than wealth." },
      { zh: "阅读能开阔视野。", en: "Reading can broaden our horizons." },
      { zh: "互联网使沟通更加便捷。", en: "The internet makes communication more convenient." },
      { zh: "我们应该重视心理健康。", en: "We should pay attention to mental health." },
      { zh: "团队合作能提高效率。", en: "Teamwork can improve efficiency." },
      { zh: "失败是成功之母。", en: "Failure is the mother of success." },
      { zh: "时间管理非常重要。", en: "Time management is very important." },
    ],
  },
  {
    id: "kaoyan", title: "考研长难句拆解", cat: "考试备考",
    emoji: "📚", cover: "blue", learners: 2680, level: "高级",
    desc: "考研英语长难句拆解，攻克阅读与写作。",
    words: [
      { en: "cooperation", zh: "合作" }, { en: "memory", zh: "记忆" }, { en: "effort", zh: "努力" },
      { en: "competition", zh: "竞争" }, { en: "phenomenon", zh: "现象" }, { en: "reflection", zh: "反思" },
      { en: "persistence", zh: "坚持" }, { en: "conclusion", zh: "结论" },
    ],
    lessons: [
      { zh: "尽管困难，他仍坚持自己的目标。", en: "Although it was difficult, he stuck to his goal." },
      { zh: "正是努力决定了最终的成果。", en: "It is effort that determines the final result." },
      { zh: "越来越多的年轻人选择创业。", en: "More and more young people choose to start businesses." },
      { zh: "只有合作才能解决这一问题。", en: "Only by cooperation can we solve this problem." },
      { zh: "研究表明睡眠影响记忆力。", en: "Studies show that sleep affects memory." },
      { zh: "不可否认，竞争日益激烈。", en: "There is no denying that competition is becoming fierce." },
      { zh: "这一现象值得深入探讨。", en: "This phenomenon deserves further discussion." },
      { zh: "只有不断反思才能进步。", en: "Only by constant reflection can we make progress." },
      { zh: "他认为成功源于坚持。", en: "He believes that success comes from persistence." },
      { zh: "综上所述，我们应理性看待。", en: "In conclusion, we should view it rationally." },
    ],
  },
  {
    id: "ielts", title: "雅思口语高频句", cat: "考试备考",
    emoji: "🗣️", cover: "purple", learners: 2210, level: "中级",
    desc: "雅思口语 Part 1-3 高频话题句型。",
    words: [
      { en: "hobby", zh: "爱好" }, { en: "travel", zh: "旅行" }, { en: "opinion", zh: "观点" },
      { en: "season", zh: "季节" }, { en: "autumn", zh: "秋天" }, { en: "childhood", zh: "童年" },
      { en: "Europe", zh: "欧洲" }, { en: "convenient", zh: "便利的" },
    ],
    lessons: [
      { zh: "我的爱好是读书。", en: "My hobby is reading." },
      { zh: "我同意这个观点。", en: "I agree with this opinion." },
      { zh: "旅行能开阔眼界。", en: "Travel broadens the mind." },
      { zh: "我喜欢我的家乡。", en: "I love my hometown." },
      { zh: "这个城市很安全。", en: "This city is very safe." },
      { zh: "我在北京住了五年了。", en: "I have lived in Beijing for five years." },
      { zh: "我最喜欢的季节是秋天。", en: "My favorite season is autumn." },
      { zh: "我常和朋友一起看电影。", en: "I usually watch movies with friends." },
      { zh: "我认为科技让生活更便利。", en: "I think technology makes life more convenient." },
      { zh: "我小时候很喜欢画画。", en: "I liked drawing when I was a child." },
      { zh: "未来我想去欧洲旅行。", en: "I want to travel to Europe in the future." },
      { zh: "这个话题很有意思。", en: "This topic is very interesting." },
    ],
  },
  {
    id: "parent", title: "亲子英语口语", cat: "亲子英语",
    emoji: "👶", cover: "green", learners: 5685, level: "入门",
    desc: "亲子日常对话，陪娃练出语感。",
    words: [
      { en: "sleep", zh: "睡觉" }, { en: "toy", zh: "玩具" }, { en: "happy", zh: "开心" },
      { en: "hands", zh: "手" }, { en: "dinner", zh: "晚餐" }, { en: "careful", zh: "小心的" },
    ],
    lessons: [
      { zh: "该睡觉了。", en: "It is time to sleep." },
      { zh: "我们读一本书吧。", en: "Let us read a book." },
      { zh: "把玩具收好。", en: "Put the toys away." },
      { zh: "你今天开心吗？", en: "Are you happy today?" },
      { zh: "妈妈爱你。", en: "Mom loves you." },
      { zh: "该起床了。", en: "It is time to get up." },
      { zh: "洗手吃饭。", en: "Wash your hands and eat." },
      { zh: "慢慢来，别着急。", en: "Take your time, no rush." },
      { zh: "做得好！", en: "Well done!" },
      { zh: "小心一点。", en: "Please be careful." },
    ],
  },
  {
    id: "kids", title: "少儿英语启蒙", cat: "亲子英语",
    emoji: "🧸", cover: "green", learners: 4325, level: "入门",
    desc: "专为小朋友设计，动物、颜色、数字轻松记。",
    words: [
      { en: "apple", zh: "苹果" }, { en: "blue", zh: "蓝色" }, { en: "dog", zh: "狗" },
      { en: "count", zh: "数数" }, { en: "bird", zh: "鸟" }, { en: "ice cream", zh: "冰淇淋" },
    ],
    lessons: [
      { zh: "我有一只小狗。", en: "I have a small dog." },
      { zh: "天空是蓝色的。", en: "The sky is blue." },
      { zh: "我爱我的妈妈。", en: "I love my mom." },
      { zh: "这是一个苹果。", en: "This is an apple." },
      { zh: "让我们去玩吧。", en: "Let us go and play." },
      { zh: "我会数到十。", en: "I can count to ten." },
      { zh: "小鸟在飞。", en: "The bird is flying." },
      { zh: "今天很热。", en: "It is hot today." },
      { zh: "我喜欢冰淇淋。", en: "I like ice cream." },
      { zh: "再见，明天见。", en: "Goodbye, see you tomorrow." },
    ],
  },
  {
    id: "biz", title: "商务英语邮件写作", cat: "商务英语",
    emoji: "✉️", cover: "orange", learners: 1980, level: "中级",
    desc: "商务邮件标准句型，专业不发愁。",
    words: [
      { en: "attachment", zh: "附件" }, { en: "reply", zh: "回复" }, { en: "meeting", zh: "会议" },
      { en: "quotation", zh: "报价单" }, { en: "decision", zh: "决定" }, { en: "details", zh: "细节" },
      { en: "proposal", zh: "方案" }, { en: "regards", zh: "问候" }, { en: "confirm", zh: "确认" },
      { en: "apologize", zh: "道歉" },
    ],
    lessons: [
      { zh: "请查收附件。", en: "Please find the attachment." },
      { zh: "期待您的回复。", en: "I look forward to your reply." },
      { zh: "我们能否安排一次会议？", en: "Could we schedule a meeting?" },
      { zh: "感谢您的时间。", en: "Thank you for your time." },
      { zh: "很荣幸与您合作。", en: "It is a pleasure to work with you." },
      { zh: "我写邮件是想询问一下。", en: "I am writing to inquire about this." },
      { zh: "请告知您的决定。", en: "Please let me know your decision." },
      { zh: "随信附上报价单。", en: "Please find the quotation attached." },
      { zh: "如有疑问请随时联系我。", en: "Please feel free to contact me with any questions." },
      { zh: "很抱歉回复晚了。", en: "I apologize for the late reply." },
      { zh: "我想确认一下细节。", en: "I would like to confirm the details." },
      { zh: "请将此邮件转发给相关人员。", en: "Please forward this email to the relevant people." },
      { zh: "我们会尽快处理。", en: "We will handle it as soon as possible." },
      { zh: "这是更新后的方案。", en: "Here is the updated proposal." },
      { zh: "感谢您的耐心与配合。", en: "Thank you for your patience and cooperation." },
      { zh: "祝商祺。", en: "Best regards." },
    ],
  },
  {
    id: "meeting", title: "商务会议英语", cat: "商务英语",
    emoji: "📊", cover: "orange", learners: 1760, level: "中级",
    desc: "开会、汇报、讨论，职场沟通更自信。",
    words: [
      { en: "agenda", zh: "议程" }, { en: "deadline", zh: "截止时间" }, { en: "report", zh: "报告" },
      { en: "background", zh: "背景" }, { en: "comment", zh: "意见" }, { en: "risky", zh: "有风险的" },
      { en: "data", zh: "数据" }, { en: "summarize", zh: "总结" }, { en: "notes", zh: "纪要" },
      { en: "scheduled", zh: "已安排的" },
    ],
    lessons: [
      { zh: "我们开始会议吧。", en: "Let us start the meeting." },
      { zh: "请看一下议程。", en: "Please review the agenda." },
      { zh: "我们需要一个截止时间。", en: "We need a deadline." },
      { zh: "我来汇报进度。", en: "I will report the progress." },
      { zh: "谢谢大家参与。", en: "Thank you all for joining." },
      { zh: "我们今天讨论三个议题。", en: "We will discuss three items today." },
      { zh: "我先说一下背景。", en: "Let me give you some background first." },
      { zh: "大家有什么意见吗？", en: "Any comments?" },
      { zh: "我同意你的看法。", en: "I agree with you." },
      { zh: "我有不同的看法。", en: "I see it differently." },
      { zh: "我们回到正题吧。", en: "Let us get back on track." },
      { zh: "这个方案风险太高。", en: "This plan is too risky." },
      { zh: "我们需要更多数据支持。", en: "We need more data to support it." },
      { zh: "请把结论总结一下。", en: "Please summarize the conclusions." },
      { zh: "下次会议定在周五。", en: "The next meeting is scheduled for Friday." },
      { zh: "请把会议纪要发给大家。", en: "Please send the meeting notes to everyone." },
    ],
  },
  {
    id: "job", title: "求职面试英语", cat: "职场商务",
    emoji: "💼", cover: "purple", learners: 2050, level: "中级",
    desc: "自我介绍、谈薪资、答追问，面试不慌。",
    words: [
      { en: "experience", zh: "经验" }, { en: "salary", zh: "薪资" }, { en: "strength", zh: "优势" },
      { en: "graduate", zh: "毕业" }, { en: "major", zh: "主修" }, { en: "industry", zh: "行业" },
      { en: "responsible", zh: "负责的" }, { en: "opportunity", zh: "机会" },
      { en: "relocate", zh: "搬迁" }, { en: "platform", zh: "平台" },
    ],
    lessons: [
      { zh: "我有很多相关经验。", en: "I have a lot of relevant experience." },
      { zh: "我的优势是细心。", en: "My strength is being careful." },
      { zh: "我对薪资很灵活。", en: "I am flexible about salary." },
      { zh: "为什么想加入我们？", en: "Why do you want to join us?" },
      { zh: "我下周可以入职。", en: "I can start next week." },
      { zh: "我毕业于北京大学。", en: "I graduated from Peking University." },
      { zh: "我主修市场营销。", en: "I majored in marketing." },
      { zh: "我负责管理客户账户。", en: "I was in charge of managing client accounts." },
      { zh: "我帮公司提升了百分之二十的业绩。", en: "I helped the company increase sales by twenty percent." },
      { zh: "我对这个行业很熟悉。", en: "I am familiar with this industry." },
      { zh: "我离职是因为公司搬迁。", en: "I left because the company relocated." },
      { zh: "我想在更大的平台上发展。", en: "I want to grow on a bigger platform." },
      { zh: "我最大的优点是学得快。", en: "My biggest strength is learning fast." },
      { zh: "我有时过于追求完美。", en: "I sometimes try to be too perfect." },
      { zh: "我五年内想成为团队负责人。", en: "I want to become a team leader within five years." },
      { zh: "我期望的月薪是一万五。", en: "My expected salary is fifteen thousand per month." },
      { zh: "这个岗位的日常职责是什么？", en: "What are the daily responsibilities of this role?" },
      { zh: "团队目前有多少人？", en: "How many people are on the team now?" },
      { zh: "我有几个问题想确认一下。", en: "I have a few questions to confirm." },
      { zh: "很高兴今天和您交流。", en: "It was a pleasure talking with you today." },
    ],
  },
  {
    id: "negotiation", title: "商务谈判英语", cat: "职场商务",
    emoji: "🤝", cover: "purple", learners: 1620, level: "高级",
    desc: "报价、让步、签单，谈判桌上稳扎稳打。",
    words: [
      { en: "discount", zh: "折扣" }, { en: "contract", zh: "合同" }, { en: "agreement", zh: "协议" },
      { en: "budget", zh: "预算" }, { en: "terms", zh: "条款" }, { en: "installment", zh: "分期付款" },
      { en: "compromise", zh: "妥协" }, { en: "confirmation", zh: "确认" },
      { en: "bulk", zh: "大批" }, { en: "smooth", zh: "顺利的" },
    ],
    lessons: [
      { zh: "我们能给一个折扣。", en: "We can offer a discount." },
      { zh: "让我们签合同吧。", en: "Let us sign the contract." },
      { zh: "我们达成了协议。", en: "We reached an agreement." },
      { zh: "价格可以再谈。", en: "The price is negotiable." },
      { zh: "这是最终报价。", en: "This is our final offer." },
      { zh: "这个价格超出了我们的预算。", en: "This price is beyond our budget." },
      { zh: "我们能各让一步吗？", en: "Can we meet in the middle?" },
      { zh: "批量采购能便宜些吗？", en: "Can we get a better price for a bulk order?" },
      { zh: "我们希望分期付款。", en: "We prefer payment by installments." },
      { zh: "让我们把条款再过一遍。", en: "Let us go over the terms again." },
      { zh: "这一点我们不能让步。", en: "We cannot compromise on this point." },
      { zh: "我们需要书面确认。", en: "We need written confirmation." },
      { zh: "如果达成一致，今天就签约。", en: "If we agree, we will sign today." },
      { zh: "期待我们的合作顺利。", en: "I look forward to a smooth cooperation." },
    ],
  },
  {
    id: "movie", title: "美剧地道口语", cat: "文化兴趣",
    emoji: "🎬", cover: "green", learners: 3890, level: "初级",
    desc: "跟美剧学最地道的生活口语。",
    words: [
      { en: "awesome", zh: "太棒了" }, { en: "really", zh: "真的" }, { en: "friend", zh: "朋友" },
      { en: "kidding", zh: "开玩笑" }, { en: "idea", zh: "主意" }, { en: "guess", zh: "猜测" },
      { en: "alone", zh: "独自的" }, { en: "mean", zh: "意思是" },
      { en: "point", zh: "意义" }, { en: "enough", zh: "足够的" },
    ],
    lessons: [
      { zh: "这太棒了！", en: "That is awesome!" },
      { zh: "你真的这么想吗？", en: "Do you really think so?" },
      { zh: "我们是好朋友。", en: "We are good friends." },
      { zh: "别担心。", en: "Do not worry." },
      { zh: "明天见。", en: "See you tomorrow." },
      { zh: "你开玩笑吧？", en: "Are you kidding me?" },
      { zh: "别闹了。", en: "Come on." },
      { zh: "我受够了。", en: "I have had enough." },
      { zh: "这不关你的事。", en: "It is none of your business." },
      { zh: "你说得对。", en: "You are right about that." },
      { zh: "我完全不知道。", en: "I have no idea." },
      { zh: "我马上回来。", en: "I will be right back." },
      { zh: "我猜也是。", en: "I guess so." },
      { zh: "随你便。", en: "Suit yourself." },
      { zh: "我觉得我们该走了。", en: "I think we should get going." },
      { zh: "这有什么意义？", en: "What is the point of this?" },
      { zh: "别管我。", en: "Leave me alone." },
      { zh: "我不是故意的。", en: "I did not mean it." },
      { zh: "你先请。", en: "After you." },
      { zh: "好久不见。", en: "It has been a long time." },
    ],
  },
  {
    id: "idiom", title: "英语习语俚语", cat: "文化兴趣",
    emoji: "✨", cover: "green", learners: 2740, level: "中级",
    desc: "地道习语俚语，让表达更 native。",
    words: [
      { en: "piece", zh: "片" }, { en: "cake", zh: "蛋糕" }, { en: "rain", zh: "雨" },
      { en: "opportunity", zh: "机会" }, { en: "secret", zh: "秘密" }, { en: "story", zh: "故事" },
      { en: "deal", zh: "交易" }, { en: "beans", zh: "豆子" },
      { en: "patient", zh: "耐心的" }, { en: "serious", zh: "认真的" },
    ],
    lessons: [
      { zh: "这小菜一碟。", en: "It is a piece of cake." },
      { zh: "当心，要下雨了。", en: "Watch out, it is going to rain." },
      { zh: "他让我抓狂。", en: "He drives me crazy." },
      { zh: "我们言归正传。", en: "Let us get back to business." },
      { zh: "我懂你的意思。", en: "I get what you mean." },
      { zh: "别着急，慢慢来。", en: "Take it easy." },
      { zh: "这是个千载难逢的机会。", en: "This is a golden opportunity." },
      { zh: "他是个大人物。", en: "He is a big shot." },
      { zh: "我们扯平了。", en: "We are even." },
      { zh: "说来话长。", en: "It is a long story." },
      { zh: "别泄露秘密。", en: "Do not spill the beans." },
      { zh: "他临阵退缩了。", en: "He got cold feet." },
      { zh: "我们意见一致。", en: "We are on the same page." },
      { zh: "别小题大做。", en: "Do not make a mountain out of a molehill." },
      { zh: "我们走着瞧。", en: "Let us wait and see." },
      { zh: "这很划算。", en: "It is a good deal." },
      { zh: "他是认真的。", en: "He means business." },
      { zh: "耐心是一种美德。", en: "Patience is a virtue." },
    ],
  },
  {
    id: "tech", title: "IT科技英语", cat: "职场商务",
    emoji: "💻", cover: "purple", learners: 1880, level: "中级",
    desc: "编程、产品、会议，科技职场用语。",
    words: [
      { en: "code", zh: "代码" }, { en: "deploy", zh: "部署" }, { en: "bug", zh: "漏洞" },
      { en: "server", zh: "服务器" }, { en: "feature", zh: "功能" }, { en: "review", zh: "审查" },
      { en: "production", zh: "生产环境" }, { en: "solution", zh: "方案" },
    ],
    lessons: [
      { zh: "我来写这段代码。", en: "I will write this code." },
      { zh: "我们部署了新版本。", en: "We deployed a new version." },
      { zh: "有一个 bug 要修。", en: "There is a bug to fix." },
      { zh: "请提交你的方案。", en: "Please submit your proposal." },
      { zh: "系统在维护中。", en: "The system is under maintenance." },
      { zh: "我需要审查这段代码。", en: "I need to review this code." },
      { zh: "这个功能还没完成。", en: "This feature is not finished yet." },
      { zh: "我们把它发布到生产环境。", en: "We will put it into production." },
      { zh: "服务器宕机了。", en: "The server is down." },
      { zh: "请提交一个工单。", en: "Please open a ticket." },
      { zh: "我们需要一个技术方案。", en: "We need a technical solution." },
      { zh: "接口返回了一个错误。", en: "The API returned an error." },
    ],
  },

  /* ===== 以下为本轮新增：旅游 / 面试 / 商务 / 地道表达 ===== */
  {
    id: "travelpro", title: "出境自由行实战英语", cat: "日常口语",
    emoji: "🌍", cover: "purple", learners: 3120, level: "中级",
    desc: "值机、海关、酒店、问路、退税、应急——一次出国全流程会说。",
    words: [
      { en: "passport", zh: "护照" }, { en: "customs", zh: "海关" }, { en: "declare", zh: "申报" },
      { en: "reservation", zh: "预订" }, { en: "check", zh: "检查" }, { en: "refund", zh: "退款" },
      { en: "wallet", zh: "钱包" }, { en: "pharmacy", zh: "药房" },
      { en: "address", zh: "地址" }, { en: "emergency", zh: "紧急情况" },
    ],
    lessons: [
      { zh: "我要办理登机手续。", en: "I would like to check in for my flight." },
      { zh: "这件行李要托运。", en: "I need to check in this luggage." },
      { zh: "这个可以带上飞机吗？", en: "Can I carry this on board?" },
      { zh: "我的座位靠窗。", en: "My seat is by the window." },
      { zh: "我是来旅游的。", en: "I am here on vacation." },
      { zh: "我会待七天。", en: "I will stay for seven days." },
      { zh: "这是我第一次来这里。", en: "This is my first time here." },
      { zh: "请问海关在哪里？", en: "Where is customs please?" },
      { zh: "我没有东西要申报。", en: "I have nothing to declare." },
      { zh: "我有一个预订。", en: "I have a reservation." },
      { zh: "能给我房间钥匙吗？", en: "Could I have my room key?" },
      { zh: "房间里没有热水。", en: "There is no hot water in the room." },
      { zh: "我想换一个房间。", en: "I would like to change my room." },
      { zh: "我明天退房。", en: "I am checking out tomorrow." },
      { zh: "请问怎么去地铁站？", en: "How do I get to the subway station?" },
      { zh: "到机场要多久？", en: "How long does it take to the airport?" },
      { zh: "请带我去这个地址。", en: "Please take me to this address." },
      { zh: "附近有药房吗？", en: "Is there a pharmacy nearby?" },
      { zh: "可以帮我退一下税吗？", en: "Can I get a tax refund?" },
      { zh: "我的钱包丢了。", en: "I lost my wallet." },
    ],
  },
  {
    id: "interview", title: "外企面试实战英语", cat: "职场商务",
    emoji: "🎯", cover: "purple", learners: 2460, level: "高级",
    desc: "行为面试、压力问答、反问环节，外企面试全套话术。",
    words: [
      { en: "briefly", zh: "简要地" }, { en: "achievement", zh: "成就" }, { en: "conflict", zh: "冲突" },
      { en: "pressure", zh: "压力" }, { en: "weakness", zh: "缺点" }, { en: "culture", zh: "文化" },
      { en: "candidate", zh: "候选人" }, { en: "promotion", zh: "晋升" },
      { en: "remote", zh: "远程的" }, { en: "notice", zh: "通知期" },
    ],
    lessons: [
      { zh: "我简单介绍一下自己。", en: "Let me briefly introduce myself." },
      { zh: "我在这个领域有八年经验。", en: "I have eight years of experience in this field." },
      { zh: "我上一份工作是项目经理。", en: "My previous role was project manager." },
      { zh: "我带领过一个十人的团队。", en: "I led a team of ten people." },
      { zh: "我最大的成就是完成了那次转型。", en: "My greatest achievement was completing that transformation." },
      { zh: "我离职是为了寻找新的挑战。", en: "I left to look for new challenges." },
      { zh: "我的优点是抗压能力强。", en: "My strength is working well under pressure." },
      { zh: "我的缺点是有时过于关注细节。", en: "My weakness is that I sometimes focus too much on details." },
      { zh: "我正在努力改进这一点。", en: "I am working on improving that." },
      { zh: "我曾经处理过一次团队冲突。", en: "I once handled a team conflict." },
      { zh: "我倾向于先倾听再决策。", en: "I tend to listen first and then decide." },
      { zh: "为什么我适合这个岗位？", en: "Why am I a good fit for this role?" },
      { zh: "我非常欣赏贵公司的文化。", en: "I really admire your company culture." },
      { zh: "我更看重成长机会。", en: "I value growth opportunities more." },
      { zh: "这个岗位可以远程办公吗？", en: "Is this position open to remote work?" },
      { zh: "我的通知期是两周。", en: "My notice period is two weeks." },
      { zh: "能介绍一下这个团队吗？", en: "Could you tell me about the team?" },
      { zh: "这个岗位的晋升路径是怎样的？", en: "What does the career path for this role look like?" },
      { zh: "接下来的流程是什么？", en: "What are the next steps?" },
      { zh: "感谢您的时间，期待您的回复。", en: "Thank you for your time and I look forward to hearing from you." },
    ],
  },
  {
    id: "biztalk", title: "商务沟通进阶", cat: "商务英语",
    emoji: "📞", cover: "orange", learners: 1580, level: "高级",
    desc: "电话会议、跟进催办、异议处理、坏消息汇报与危机补救。",
    words: [
      { en: "follow", zh: "跟进" }, { en: "consensus", zh: "共识" }, { en: "concern", zh: "顾虑" },
      { en: "pilot", zh: "试点" }, { en: "delay", zh: "延期" }, { en: "loss", zh: "损失" },
      { en: "apologize", zh: "道歉" }, { en: "inconvenience", zh: "不便" },
      { en: "partnership", zh: "合作关系" }, { en: "mutual", zh: "共同的" },
    ],
    lessons: [
      { zh: "我打电话是想跟进一下。", en: "I am calling to follow up." },
      { zh: "我们能把会议提前吗？", en: "Could we move the meeting earlier?" },
      { zh: "我这边信号不太好。", en: "I have a bad connection on my end." },
      { zh: "能麻烦您重复一下吗？", en: "Could you repeat that please?" },
      { zh: "我来确认一下要点。", en: "Let me confirm the key points." },
      { zh: "我们已经达成了共识。", en: "We have reached a consensus." },
      { zh: "我理解您的顾虑。", en: "I understand your concern." },
      { zh: "让我换个方式说明。", en: "Let me put it another way." },
      { zh: "我们可以先做一个试点。", en: "We could start with a pilot." },
      { zh: "这个问题我来跟进。", en: "I will take care of this issue." },
      { zh: "恐怕我们不得不延期交付。", en: "I am afraid we have to delay the delivery." },
      { zh: "这次的损失由我们承担。", en: "We will cover the loss this time." },
      { zh: "给您带来不便，非常抱歉。", en: "We apologize for the inconvenience." },
      { zh: "感谢您的理解与耐心。", en: "Thank you for your understanding and patience." },
      { zh: "希望我们继续保持合作。", en: "I hope we can continue our cooperation." },
      { zh: "请把合同发给我确认。", en: "Please send me the contract for confirmation." },
      { zh: "我们对这次合作很有信心。", en: "We are confident about this partnership." },
      { zh: "期待长期共赢的关系。", en: "We look forward to a long-term mutually beneficial relationship." },
    ],
  },
  {
    id: "slang", title: "地道口语金句", cat: "地道表达",
    emoji: "🔥", cover: "green", learners: 4320, level: "中级",
    desc: "native 天天在说的口头禅，学会就能听懂美剧和播客。",
    words: [
      { en: "honest", zh: "诚实的" }, { en: "worry", zh: "担心" }, { en: "tired", zh: "疲倦的" },
      { en: "fair", zh: "公平的" }, { en: "favor", zh: "帮忙" }, { en: "chase", zh: "追逐" },
      { en: "stretch", zh: "牵强" }, { en: "support", zh: "支持" },
      { en: "sort", zh: "种类" }, { en: "bet", zh: "打赌" },
    ],
    lessons: [
      { zh: "我没问题，算我一个。", en: "I am down." },
      { zh: "没关系，别客气。", en: "No worries." },
      { zh: "说实话。", en: "To be honest." },
      { zh: "长话短说。", en: "Long story short." },
      { zh: "这对我很合适。", en: "That works for me." },
      { zh: "由你决定。", en: "It is up to you." },
      { zh: "我懂你的感受。", en: "I feel you." },
      { zh: "有道理。", en: "Fair enough." },
      { zh: "我累坏了。", en: "I am beat." },
      { zh: "今天就到此为止吧。", en: "Let us call it a day." },
      { zh: "我洗耳恭听。", en: "I am all ears." },
      { zh: "别绕弯子，说重点。", en: "Cut to the chase." },
      { zh: "是我的错。", en: "My bad." },
      { zh: "差不多吧。", en: "Sort of." },
      { zh: "当然，没问题。", en: "You bet." },
      { zh: "坚持一下。", en: "Hang in there." },
      { zh: "别开玩笑了。", en: "Get out of here." },
      { zh: "这有点牵强。", en: "That is a stretch." },
      { zh: "随它去吧。", en: "Let it go." },
      { zh: "我挺你。", en: "I have got your back." },
    ],
  },
  {
    id: "beauty", title: "优美英文表达", cat: "地道表达",
    emoji: "🌅", cover: "blue", learners: 2980, level: "中级",
    desc: "值得背诵的优美谚语与金句，写作文、发朋友圈都能用。",
    words: [
      { en: "silver", zh: "银色的" }, { en: "journey", zh: "旅程" }, { en: "silence", zh: "沉默" },
      { en: "contentment", zh: "满足" }, { en: "grateful", zh: "感激的" }, { en: "moment", zh: "当下" },
      { en: "beginning", zh: "开始" }, { en: "possible", zh: "可能的" },
      { en: "patience", zh: "耐心" }, { en: "tomorrow", zh: "明天" },
    ],
    lessons: [
      { zh: "黑暗中总有一线光明。", en: "Every cloud has a silver lining." },
      { zh: "最好的尚未到来。", en: "The best is yet to come." },
      { zh: "事实胜于雄辩。", en: "Actions speak louder than words." },
      { zh: "心之所向，便是家。", en: "Home is where the heart is." },
      { zh: "光阴似箭。", en: "Time flies." },
      { zh: "少即是多。", en: "Less is more." },
      { zh: "稳扎稳打，方能致远。", en: "Slow and steady wins the race." },
      { zh: "沉默是金。", en: "Silence is golden." },
      { zh: "知足常乐。", en: "Happiness lies in contentment." },
      { zh: "千里之行，始于足下。", en: "A journey of a thousand miles begins with a single step." },
      { zh: "不经历风雨，怎么见彩虹。", en: "No pain no gain." },
      { zh: "岁月不待人。", en: "Time and tide wait for no man." },
      { zh: "一切皆有可能。", en: "Anything is possible." },
      { zh: "好东西值得等待。", en: "Good things are worth waiting for." },
      { zh: "每一个结束都是新的开始。", en: "Every ending is a new beginning." },
      { zh: "活在当下。", en: "Live in the moment." },
      { zh: "感恩你所拥有的一切。", en: "Be grateful for what you have." },
      { zh: "明天又是新的一天。", en: "Tomorrow is another day." },
    ],
  },
  {
    id: "react", title: "情绪与反应地道表达", cat: "地道表达",
    emoji: "💗", cover: "green", learners: 3210, level: "中级",
    desc: "惊讶、安慰、夸赞、鼓励——native 脱口而出的情绪反应句。",
    words: [
      { en: "proud", zh: "骄傲的" }, { en: "relieved", zh: "松一口气的" }, { en: "nervous", zh: "紧张的" },
      { en: "disappointing", zh: "令人失望的" }, { en: "coincidence", zh: "巧合" }, { en: "shame", zh: "遗憾" },
      { en: "excite", zh: "使兴奋" }, { en: "encourage", zh: "鼓励" },
      { en: "patient", zh: "耐心的" }, { en: "believe", zh: "相信" },
    ],
    lessons: [
      { zh: "我真为你高兴。", en: "I am so happy for you." },
      { zh: "振作起来。", en: "Cheer up." },
      { zh: "我完全能理解。", en: "I can relate." },
      { zh: "这太令人兴奋了。", en: "That is so exciting." },
      { zh: "我简直不敢相信。", en: "I cannot believe it." },
      { zh: "真巧啊。", en: "What a coincidence." },
      { zh: "干得漂亮。", en: "Nice work." },
      { zh: "你做到了！", en: "You did it." },
      { zh: "别放弃。", en: "Do not give up." },
      { zh: "慢慢来，不着急。", en: "Take your time." },
      { zh: "我为你感到骄傲。", en: "I am proud of you." },
      { zh: "这真让人失望。", en: "That is disappointing." },
      { zh: "我有点紧张。", en: "I am a little nervous." },
      { zh: "我总算松了一口气。", en: "I am so relieved." },
      { zh: "这让我很感动。", en: "That really touched me." },
      { zh: "谢谢你一直陪着我。", en: "Thank you for always being there." },
      { zh: "真遗憾。", en: "That is a shame." },
      { zh: "小心一点。", en: "Be careful." },
    ],
  },
  {
    id: "smalltalk", title: "日常寒暄闲聊", cat: "日常口语",
    emoji: "☕", cover: "orange", learners: 2760, level: "初级",
    desc: "见面打招呼、破冰闲聊、体面告别，社交不再冷场。",
    words: [
      { en: "weekend", zh: "周末" }, { en: "weather", zh: "天气" }, { en: "traffic", zh: "交通" },
      { en: "hometown", zh: "家乡" }, { en: "hobbies", zh: "爱好" }, { en: "touch", zh: "联系" },
      { en: "drink", zh: "饮料" }, { en: "busy", zh: "忙碌的" },
    ],
    lessons: [
      { zh: "你好吗？", en: "How are you doing?" },
      { zh: "最近怎么样？", en: "How have you been?" },
      { zh: "很高兴见到你。", en: "It is nice to see you." },
      { zh: "周末过得怎么样？", en: "How was your weekend?" },
      { zh: "今天天气不错。", en: "The weather is nice today." },
      { zh: "你今天气色很好。", en: "You look great today." },
      { zh: "路上堵车吗？", en: "Was the traffic heavy?" },
      { zh: "想喝点什么吗？", en: "Would you like something to drink?" },
      { zh: "你是哪里人？", en: "Where are you from?" },
      { zh: "你做什么工作？", en: "What do you do?" },
      { zh: "你有什么爱好？", en: "What are your hobbies?" },
      { zh: "最近忙吗？", en: "Have you been busy lately?" },
      { zh: "我得走了。", en: "I have to get going." },
      { zh: "保持联系。", en: "Let us keep in touch." },
      { zh: "祝你今天愉快。", en: "Have a great day." },
      { zh: "回头聊。", en: "Talk to you later." },
    ],
  },
];

// 课程分类（用于筛选）
const CATEGORIES = ["全部", "零基础", "教材同步", "日常口语", "考试备考", "亲子英语", "商务英语", "职场商务", "文化兴趣", "地道表达"];

// 排行榜示例数据
const LEADERBOARD = [
  { name: "英语狂人", done: 18420, minutes: 9200 },
  { name: "小语同学", done: 15230, minutes: 7600 },
  { name: "每天打卡", done: 13980, minutes: 7100 },
  { name: "Leo", done: 11200, minutes: 5400 },
  { name: "背词机器", done: 9870, minutes: 4900 },
  { name: "果果妈", done: 8650, minutes: 4300 },
  { name: "Tom老师", done: 7340, minutes: 3600 },
  { name: "夜跑选手", done: 6210, minutes: 3100 },
];
