/* ===== 硬核英语社 · 示例数据 =====
 * 说明：以下课程与句子为示例数据。
 */
const COURSES = [
  {
    id: "basics", title: "零基础学英语（动物·星期·水果）", cat: "零基础",
    emoji: "🐱", cover: "green", learners: 7600, level: "入门",
    desc: "从字母和基础句型起步，认识动物、星期、水果等最常用表达。",
    words: [{ en: "cat", zh: "猫" }, { en: "Wednesday", zh: "星期三" }, { en: "apple", zh: "苹果" }],
    lessons: [
      { zh: "我是一只猫。", en: "I am a cat." },
      { zh: "今天星期三。", en: "Today is Wednesday." },
      { zh: "她喜欢苹果。", en: "She likes apples." },
      { zh: "那是一只狗。", en: "That is a dog." },
      { zh: "我们吃香蕉。", en: "We eat bananas." },
    ],
  },
  {
    id: "grammar", title: "语法渐进式突破", cat: "零基础",
    emoji: "🧩", cover: "green", learners: 7532, level: "初级",
    desc: "用最直白的例句讲清时态、句型与主谓宾，搭好语法骨架。",
    words: [{ en: "teacher", zh: "老师" }, { en: "running", zh: "跑步" }, { en: "interesting", zh: "有趣的" }],
    lessons: [
      { zh: "她是一个老师。", en: "She is a teacher." },
      { zh: "他们正在跑步。", en: "They are running." },
      { zh: "我昨天看了电影。", en: "I watched a movie yesterday." },
      { zh: "这本书很有趣。", en: "This book is interesting." },
      { zh: "如果下雨我们就待在家。", en: "If it rains we will stay at home." },
    ],
  },
  {
    id: "nc1", title: "新概念英语 第1册", cat: "教材同步",
    emoji: "📘", cover: "blue", learners: 3855, level: "初级",
    desc: "经典新概念第一册，短句打磨听说基础。",
    words: [{ en: "umbrella", zh: "雨伞" }, { en: "London", zh: "伦敦" }, { en: "tea", zh: "茶" }],
    lessons: [
      { zh: "很高兴见到你。", en: "Nice to meet you." },
      { zh: "这是你的伞吗？", en: "Is this your umbrella?" },
      { zh: "他正在看书。", en: "He is reading a book." },
      { zh: "请给我一杯茶。", en: "Please give me a cup of tea." },
      { zh: "他们明天去伦敦。", en: "They will go to London tomorrow." },
    ],
  },
  {
    id: "nc2", title: "新概念英语 第2册", cat: "教材同步",
    emoji: "📗", cover: "blue", learners: 3640, level: "中级",
    desc: "新概念第二册，复合句与叙事表达进阶。",
    words: [{ en: "neighbor", zh: "邻居" }, { en: "airport", zh: "机场" }, { en: "suddenly", zh: "突然" }],
    lessons: [
      { zh: "我的邻居是个飞行员。", en: "My neighbor is a pilot." },
      { zh: "他昨天到达了北京。", en: "He arrived in Beijing yesterday." },
      { zh: "请把窗户关上。", en: "Please close the window." },
      { zh: "她正在花园里工作。", en: "She is working in the garden." },
      { zh: "我们度过了一个美妙的夜晚。", en: "We had a wonderful evening." },
    ],
  },
  {
    id: "nc3", title: "新概念英语 第3册", cat: "教材同步",
    emoji: "📙", cover: "blue", learners: 3402, level: "高级",
    desc: "新概念第三册，长难句与地道表达。",
    words: [{ en: "disaster", zh: "灾难" }, { en: "ancient", zh: "古老的" }, { en: "silence", zh: "寂静" }],
    lessons: [
      { zh: "事故的原因尚未查明。", en: "The cause of the accident remains unknown." },
      { zh: "这座古城有悠久的历史。", en: "The ancient city has a long history." },
      { zh: "他保持着沉默。", en: "He remained in silence." },
      { zh: "我们应该从中吸取教训。", en: "We should learn a lesson from it." },
      { zh: "天气影响了我们的计划。", en: "The weather affected our plan." },
    ],
  },
  {
    id: "primary", title: "小学英语同步·三年级上", cat: "教材同步",
    emoji: "🎒", cover: "blue", learners: 4100, level: "入门",
    desc: "贴合小学三年级上册进度，课内同步练句型。",
    words: [{ en: "school", zh: "学校" }, { en: "red", zh: "红色" }, { en: "friend", zh: "朋友" }],
    lessons: [
      { zh: "这是我的学校。", en: "This is my school." },
      { zh: "我喜欢红色。", en: "I like red." },
      { zh: "他是我的好朋友。", en: "He is my good friend." },
      { zh: "我们有一只猫。", en: "We have a cat." },
      { zh: "早上好，老师。", en: "Good morning, teacher." },
    ],
  },
  {
    id: "daily900", title: "日常口语900句", cat: "日常口语",
    emoji: "💬", cover: "orange", learners: 4040, level: "初级",
    desc: "覆盖生活高频场景，900句日常表达随练随用。",
    words: [{ en: "restaurant", zh: "餐厅" }, { en: "help", zh: "帮助" }, { en: "time", zh: "时间" }],
    lessons: [
      { zh: "你能帮我一下吗？", en: "Can you help me please?" },
      { zh: "我在学英语。", en: "I am learning English." },
      { zh: "这家餐厅很好吃。", en: "This restaurant is very delicious." },
      { zh: "我们走吧。", en: "Let us go." },
      { zh: "现在几点了？", en: "What time is it now?" },
    ],
  },
  {
    id: "travel", title: "旅游英语口语", cat: "日常口语",
    emoji: "✈️", cover: "purple", learners: 2240, level: "初级",
    desc: "出国旅行必备口语，机场、问路、购物全搞定。",
    words: [{ en: "airport", zh: "机场" }, { en: "ticket", zh: "票" }, { en: "restroom", zh: "洗手间" }],
    lessons: [
      { zh: "我要去机场。", en: "I want to go to the airport." },
      { zh: "一张去北京的票。", en: "One ticket to Beijing." },
      { zh: "厕所在哪里？", en: "Where is the restroom?" },
      { zh: "这个多少钱？", en: "How much is this?" },
      { zh: "请帮我拍照。", en: "Please take a photo for me." },
    ],
  },
  {
    id: "food", title: "餐饮英语口语", cat: "日常口语",
    emoji: "🍜", cover: "orange", learners: 2560, level: "初级",
    desc: "点餐、评价、买单，餐桌英语不冷场。",
    words: [{ en: "menu", zh: "菜单" }, { en: "delicious", zh: "美味的" }, { en: "bill", zh: "账单" }],
    lessons: [
      { zh: "请给我菜单。", en: "Please give me the menu." },
      { zh: "这道菜很好吃。", en: "This dish is delicious." },
      { zh: "我想买单。", en: "I would like the bill." },
      { zh: "你们有什么推荐？", en: "What do you recommend?" },
      { zh: "我要一杯咖啡。", en: "I would like a cup of coffee." },
    ],
  },
  {
    id: "health", title: "健康生活英语", cat: "日常口语",
    emoji: "💪", cover: "orange", learners: 1980, level: "初级",
    desc: "看医生、健身、作息，健康话题随身练。",
    words: [{ en: "doctor", zh: "医生" }, { en: "exercise", zh: "锻炼" }, { en: "healthy", zh: "健康的" }],
    lessons: [
      { zh: "我需要看医生。", en: "I need to see a doctor." },
      { zh: "每天锻炼很重要。", en: "Daily exercise is important." },
      { zh: "保持健康的饮食。", en: "Keep a healthy diet." },
      { zh: "我感冒了。", en: "I have a cold." },
      { zh: "早点睡觉。", en: "Go to bed early." },
    ],
  },
  {
    id: "cet", title: "四六级核心句子", cat: "考试备考",
    emoji: "🎓", cover: "purple", learners: 3120, level: "中级",
    desc: "四六级高频写作句型，背熟就能用。",
    words: [{ en: "education", zh: "教育" }, { en: "environment", zh: "环境" }, { en: "technology", zh: "科技" }],
    lessons: [
      { zh: "教育对个人发展至关重要。", en: "Education is vital to personal development." },
      { zh: "我们应当保护环境。", en: "We should protect the environment." },
      { zh: "科技改变了我们的生活方式。", en: "Technology has changed our way of life." },
      { zh: "健康比财富更重要。", en: "Health is more important than wealth." },
      { zh: "阅读能开阔视野。", en: "Reading can broaden our horizons." },
    ],
  },
  {
    id: "kaoyan", title: "考研长难句拆解", cat: "考试备考",
    emoji: "📚", cover: "blue", learners: 2680, level: "高级",
    desc: "考研英语长难句拆解，攻克阅读与写作。",
    words: [{ en: "cooperation", zh: "合作" }, { en: "memory", zh: "记忆" }, { en: "effort", zh: "努力" }],
    lessons: [
      { zh: "尽管困难，他仍坚持自己的目标。", en: "Although it was difficult, he stuck to his goal." },
      { zh: "正是努力决定了最终的成果。", en: "It is effort that determines the final result." },
      { zh: "越来越多的年轻人选择创业。", en: "More and more young people choose to start businesses." },
      { zh: "只有合作才能解决这一问题。", en: "Only by cooperation can we solve this problem." },
      { zh: "研究表明睡眠影响记忆力。", en: "Studies show that sleep affects memory." },
    ],
  },
  {
    id: "ielts", title: "雅思口语高频句", cat: "考试备考",
    emoji: "🗣️", cover: "purple", learners: 2210, level: "中级",
    desc: "雅思口语 Part 1-3 高频话题句型。",
    words: [{ en: "hobby", zh: "爱好" }, { en: "travel", zh: "旅行" }, { en: "opinion", zh: "观点" }],
    lessons: [
      { zh: "我的爱好是读书。", en: "My hobby is reading." },
      { zh: "我同意这个观点。", en: "I agree with this opinion." },
      { zh: "旅行能开阔眼界。", en: "Travel broadens the mind." },
      { zh: "我喜欢我的家乡。", en: "I love my hometown." },
      { zh: "这个城市很安全。", en: "This city is very safe." },
    ],
  },
  {
    id: "parent", title: "亲子英语口语2000句", cat: "亲子英语",
    emoji: "👶", cover: "green", learners: 5685, level: "入门",
    desc: "亲子日常对话，陪娃练出语感。",
    words: [{ en: "sleep", zh: "睡觉" }, { en: "toy", zh: "玩具" }, { en: "happy", zh: "开心" }],
    lessons: [
      { zh: "该睡觉了。", en: "It is time to sleep." },
      { zh: "我们读一本书吧。", en: "Let us read a book." },
      { zh: "把玩具收好。", en: "Put the toys away." },
      { zh: "你今天开心吗？", en: "Are you happy today?" },
      { zh: "妈妈爱你。", en: "Mom loves you." },
    ],
  },
  {
    id: "kids", title: "少儿英语启蒙300句", cat: "亲子英语",
    emoji: "🧸", cover: "green", learners: 4325, level: "入门",
    desc: "专为小朋友设计，动物、颜色、数字轻松记。",
    words: [{ en: "apple", zh: "苹果" }, { en: "blue", zh: "蓝色" }, { en: "dog", zh: "狗" }],
    lessons: [
      { zh: "我有一只小狗。", en: "I have a small dog." },
      { zh: "天空是蓝色的。", en: "The sky is blue." },
      { zh: "我爱我的妈妈。", en: "I love my mom." },
      { zh: "这是一个苹果。", en: "This is an apple." },
      { zh: "让我们去玩吧。", en: "Let us go and play." },
    ],
  },
  {
    id: "biz", title: "商务英语邮件写作", cat: "商务英语",
    emoji: "✉️", cover: "orange", learners: 1980, level: "中级",
    desc: "商务邮件标准句型，专业不发愁。",
    words: [{ en: "attachment", zh: "附件" }, { en: "reply", zh: "回复" }, { en: "meeting", zh: "会议" }],
    lessons: [
      { zh: "请查收附件。", en: "Please find the attachment." },
      { zh: "期待您的回复。", en: "I look forward to your reply." },
      { zh: "我们能否安排一次会议？", en: "Could we schedule a meeting?" },
      { zh: "感谢您的时间。", en: "Thank you for your time." },
      { zh: "很荣幸与您合作。", en: "It is a pleasure to work with you." },
    ],
  },
  {
    id: "meeting", title: "商务会议英语", cat: "商务英语",
    emoji: "📊", cover: "orange", learners: 1760, level: "中级",
    desc: "开会、汇报、讨论，职场沟通更自信。",
    words: [{ en: "agenda", zh: "议程" }, { en: "deadline", zh: "截止时间" }, { en: "report", zh: "报告" }],
    lessons: [
      { zh: "我们开始会议吧。", en: "Let us start the meeting." },
      { zh: "请看一下议程。", en: "Please review the agenda." },
      { zh: "我们需要一个截止时间。", en: "We need a deadline." },
      { zh: "我来汇报进度。", en: "I will report the progress." },
      { zh: "谢谢大家参与。", en: "Thank you all for joining." },
    ],
  },
  {
    id: "job", title: "求职面试英语", cat: "职场商务",
    emoji: "💼", cover: "purple", learners: 2050, level: "中级",
    desc: "自我介绍、谈薪资、答追问，面试不慌。",
    words: [{ en: "experience", zh: "经验" }, { en: "salary", zh: "薪资" }, { en: "strength", zh: "优势" }],
    lessons: [
      { zh: "我有很多相关经验。", en: "I have a lot of relevant experience." },
      { zh: "我的优势是细心。", en: "My strength is being careful." },
      { zh: "我对薪资很灵活。", en: "I am flexible about salary." },
      { zh: "为什么想加入我们？", en: "Why do you want to join us?" },
      { zh: "我下周可以入职。", en: "I can start next week." },
    ],
  },
  {
    id: "negotiation", title: "商务谈判英语", cat: "职场商务",
    emoji: "🤝", cover: "purple", learners: 1620, level: "高级",
    desc: "报价、让步、签单，谈判桌上稳扎稳打。",
    words: [{ en: "discount", zh: "折扣" }, { en: "contract", zh: "合同" }, { en: "agreement", zh: "协议" }],
    lessons: [
      { zh: "我们能给一个折扣。", en: "We can offer a discount." },
      { zh: "让我们签合同吧。", en: "Let us sign the contract." },
      { zh: "我们达成了协议。", en: "We reached an agreement." },
      { zh: "价格可以再谈。", en: "The price is negotiable." },
      { zh: "这是最终报价。", en: "This is our final offer." },
    ],
  },
  {
    id: "movie", title: "美剧地道口语", cat: "文化兴趣",
    emoji: "🎬", cover: "green", learners: 3890, level: "初级",
    desc: "跟美剧学最地道的生活口语。",
    words: [{ en: "awesome", zh: "太棒了" }, { en: "really", zh: "真的" }, { en: "friend", zh: "朋友" }],
    lessons: [
      { zh: "这太棒了！", en: "That is awesome!" },
      { zh: "你真的这么想吗？", en: "Do you really think so?" },
      { zh: "我们是好朋友。", en: "We are good friends." },
      { zh: "别担心。", en: "Do not worry." },
      { zh: "明天见。", en: "See you tomorrow." },
    ],
  },
  {
    id: "idiom", title: "英语习语俚语", cat: "文化兴趣",
    emoji: "✨", cover: "green", learners: 2740, level: "中级",
    desc: "地道习语俚语，让表达更 native。",
    words: [{ en: "piece", zh: "片" }, { en: "cake", zh: "蛋糕" }, { en: "rain", zh: "雨" }],
    lessons: [
      { zh: "这小菜一碟。", en: "It is a piece of cake." },
      { zh: "当心，要下雨了。", en: "Watch out, it is going to rain." },
      { zh: "他让我抓狂。", en: "He drives me crazy." },
      { zh: "我们言归正传。", en: "Let us get back to business." },
      { zh: "我懂你的意思。", en: "I get what you mean." },
    ],
  },
  {
    id: "tech", title: "IT科技英语", cat: "职场商务",
    emoji: "💻", cover: "purple", learners: 1880, level: "中级",
    desc: "编程、产品、会议，科技职场用语。",
    words: [{ en: "code", zh: "代码" }, { en: "deploy", zh: "部署" }, { en: "bug", zh: "漏洞" }],
    lessons: [
      { zh: "我来写这段代码。", en: "I will write this code." },
      { zh: "我们部署了新版本。", en: "We deployed a new version." },
      { zh: "有一个 bug 要修。", en: "There is a bug to fix." },
      { zh: "请提交你的方案。", en: "Please submit your proposal." },
      { zh: "系统在维护中。", en: "The system is under maintenance." },
    ],
  },
];

// 课程分类（用于筛选）
const CATEGORIES = ["全部", "零基础", "教材同步", "日常口语", "考试备考", "亲子英语", "商务英语", "职场商务", "文化兴趣"];

// 排行榜示例数据
const LEADERBOARD = [
  { name: "英语狂人", done: 18420, minutes: 9200 },
  { name: "小语同学", done: 15230, minutes: 7600 },
  { name: "每天打卡", done: 13980, minutes: 7100 },
  { name: "Leo", done: 11200, minutes: 5400 },
  { name: "背词机器", done: 9870, minutes: 4900 },
  { name: "果果妈", done: 8650, minutes: 4300 },
  { name: "Tom老师", done: 7340, minutes: 3600 },
  { name: "夜跑选手", done: 6210, minutes: 3100 },
];
