/* ===== 硬核英语社 · 语法精讲数据 =====
 * 结构：GRAMMAR[课程id] = {
 *   grammar: [{ t:语法点, f:公式结构, z:中文说明, e:例句 }],   // 课程级「本课语法精讲」
 *   tips:    { "英文原句": "这句的语法/用法讲解" },              // 句子级讲解（键必须与 data.js 完全一致）
 *   words:   { "单词": "词性·搭配·易错点" },                     // 单词注解
 * }
 * 讲解文本中用反引号 `x` 标记要高亮/等宽显示的关键词。
 */
const GRAMMAR = {};
(function () {
  function C(id, grammar, tips, words) { GRAMMAR[id] = { grammar: grammar, tips: tips, words: words || {} }; }

  /* ---------- 零基础 ---------- */
  C("basics", [
    { t: "be 动词配对", f: "I am · You/We/They are · He/She/It is", z: "be 动词随主语变：I 永远配 am，他/她/它配 is，其余配 are。", e: "I am a cat." },
    { t: "第三人称单数加 -s", f: "He / She / It + 动词 + s", z: "主语是 he、she、it 或单数人名时，动词要加 -s，这是中文里没有的变化。", e: "She likes apples." },
    { t: "泛指用复数", f: "可数名词 + s / es", z: "泛指一类东西时用复数：喜欢苹果是 apples；s、x、ch、sh 结尾加 -es。", e: "We eat bananas." },
    { t: "this / that 分远近", f: "this 这个（近） · that 那个（远）", z: "指眼前近处用 this，指远一点用 that，后面都接单数。", e: "That is a dog." },
    { t: "have / has", f: "I·You·We·They have · He·She·It has", z: "表示拥有：第三人称单数用 has，其余用 have。", e: "He has a bird." },
  ], {
    "I am a cat.": "主语 `I` 永远配 `am`，写成 I is 就错了。",
    "Today is Wednesday.": "报星期几用 `Today is + 星期`；星期和月份首字母必须大写。",
    "She likes apples.": "主语 `She` 是第三人称单数，动词 `like` 要加 `-s`；`apple` 泛指多个也要加 `-s`。",
    "That is a dog.": "指远处用 `That`；第一次提到某样东西，单数前要加不定冠词 `a`。",
    "We eat bananas.": "`We` 后面动词用原形 `eat`，不加 -s；泛指香蕉用复数 `bananas`。",
    "This is my book.": "`This` 指近处；`my` 是物主代词，后面必须跟名词，不能单独用。",
    "He has a bird.": "`He` 是第三人称单数，表示「有」要用 `has`，不能用 have。",
    "I like Monday.": "星期名词首字母大写；这类专有名词前一般不加 the。",
  }, {
    cat: "名词 n.，可数，复数是 cats。",
    Wednesday: "名词 n.，星期三，首字母永远大写，中间的 d 不发音。",
    apple: "名词 n.，可数，复数 apples；元音音素前要用 an apple。",
    dog: "名词 n.，可数，复数 dogs；口语里 dog 还能指「家伙」。",
    banana: "名词 n.，可数，复数 bananas。",
    book: "名词 n.，可数，复数 books；作动词是「预订」，如 book a room。",
  });

  C("grammar", [
    { t: "现在进行时", f: "am / is / are + 动词ing", z: "表示此时此刻正在做，中文的「正在」就等于这个结构。", e: "They are running." },
    { t: "一般过去时", f: "动词 + ed（不规则动词另记）", z: "表示过去发生的事，常和 yesterday、last week 一起出现。", e: "I watched a movie yesterday." },
    { t: "现在完成时", f: "have / has + 过去分词", z: "强调「已经完成」或「对现在有影响」，中文的「已经」多对应它。", e: "I have finished my homework." },
    { t: "比较级", f: "形容词 + er + than", z: "两者比较用比较级，than 后面接被比较的对象。", e: "She is taller than me." },
    { t: "定语从句（省略引导词）", f: "名词 +（that/which）+ 句子", z: "用一个句子去修饰前面的名词，作宾语时引导词可以省略。", e: "This is the book I bought yesterday." },
  ], {
    "She is a teacher.": "主系表结构：`She`（主语）+ `is`（系动词）+ `a teacher`（表语），职业名称前要加 `a`。",
    "They are running.": "现在进行时 `are + running`，表示「正在跑」，`run` 要双写 n 再加 ing。",
    "I watched a movie yesterday.": "`watched` 是 watch 的过去式（规则加 -ed）；`yesterday` 一出现，动词就必须是过去式。",
    "This book is interesting.": "`interesting` 形容「事物有趣」；如果要说「我对它感兴趣」，用 I am interested in it。",
    "If it rains we will stay at home.": "主将从现：if 引导的条件从句用一般现在时 `rains`，主句才用将来时 `will stay`。",
    "I have finished my homework.": "现在完成时 `have + finished`，强调「作业已经做完了」，不说具体时间。",
    "She is taller than me.": "`taller` 是比较级，`than` 后面接比较的对象；口语里用 me 比 I 更自然。",
    "This is the book I bought yesterday.": "`I bought yesterday` 是定语从句，修饰 `the book`；作宾语的关系代词 that/which 被省略了。",
  }, {
    teacher: "名词 n.，可数，复数 teachers；讲某人的职业时前面加 a。",
    running: "run 的现在分词，注意双写 n 再加 -ing。",
    interesting: "形容词 adj.，修饰物；修饰人用 interested。",
    homework: "名词 n.，不可数，没有复数，也不能说 a homework。",
    taller: "tall 的比较级；三音节以上形容词要用 more，如 more beautiful。",
    yesterday: "副词 adv.，和一般过去时绑定使用。",
  });

  C("nc1", [
    { t: "一般疑问句", f: "be / 助动词提到句首 + ？", z: "把 is、are、do 提到句首就变成疑问句，读的时候句尾升调。", e: "Is this your umbrella?" },
    { t: "祈使句", f: "动词原形开头", z: "请求或命令直接以动词原形开头，省略主语 you。", e: "Please give me a cup of tea." },
    { t: "一般将来时", f: "will + 动词原形", z: "表示将要做的事，will 后面永远跟动词原形。", e: "They will go to London tomorrow." },
    { t: "双宾语", f: "give + 人 + 物", z: "give、send、show 这类动词后面先接人再接物。", e: "Please give me a cup of tea." },
  ], {
    "Nice to meet you.": "初次见面的固定说法，省略了 It is；回答常说 Nice to meet you too。",
    "Is this your umbrella?": "一般疑问句：把 `Is` 提到句首，句尾读升调；`your` 后面必须跟名词。",
    "He is reading a book.": "现在进行时 `is + reading`，表示此刻正在看书。",
    "Please give me a cup of tea.": "祈使句用动词原形开头；`give` 后面先接人 `me` 再接物；`a cup of` 是量词短语。",
    "They will go to London tomorrow.": "`will + go` 构成将来时，will 后面永远用原形；城市名前不加 the。",
    "What is your name?": "特殊疑问句：疑问词 `What` 开头，后面接一般疑问句语序。",
    "I am fine, thank you.": "回答 How are you 的标准说法；`fine` 是形容词作表语。",
    "Goodbye, see you tomorrow.": "告别固定表达；`see you + 时间` 表示「某时见」。",
  }, {
    umbrella: "名词 n.，可数，复数 umbrellas；元音前用 an umbrella。",
    London: "专有名词，伦敦，首字母大写，前面不加 the。",
    tea: "名词 n.，不可数；一杯茶说 a cup of tea。",
    name: "名词 n.，可数；问名字用 What is your name。",
    fine: "形容词 adj.，身体好、还不错；比 good 更常用于回答问候。",
    goodbye: "感叹词，再见，比 bye 稍正式。",
  });

  C("nc2", [
    { t: "一般过去时（不规则动词）", f: "arrive→arrived · have→had · say→said", z: "过去式多数加 -ed，但常用动词多为不规则变化，需要单独记。", e: "He arrived in Beijing yesterday." },
    { t: "现在完成时 + never", f: "have / has + never + 过去分词", z: "never 插在 have 和过去分词之间，表示「从未」。", e: "I have never been there." },
    { t: "过去将来时", f: "would + 动词原形", z: "站在过去看将来：他说「明天会下雨」，英文用 would。", e: "He said it would rain tomorrow." },
    { t: "in / at / on 的用法", f: "in 大地点 · at 小地点 · on 具体表面", z: "到达大城市用 arrive in，到机场、车站等小地点用 arrive at。", e: "He arrived in Beijing yesterday." },
  ], {
    "My neighbor is a pilot.": "主系表结构；职业名词前加 `a`，`a pilot` 是表语。",
    "He arrived in Beijing yesterday.": "`arrived` 是过去式；到达大城市用 `arrive in`，到车站机场等小地点用 arrive at。",
    "Please close the window.": "祈使句：动词原形开头；双方都知道的那扇窗要加 `the`。",
    "She is working in the garden.": "现在进行时；`in the garden` 表示在花园这个空间里。",
    "We had a wonderful evening.": "`had` 是 have 的过去式；`a wonderful evening` 是「一个美好的夜晚」。",
    "I have never been there.": "现在完成时 `have been` 表示「去过」；`never` 放在 have 和 been 中间。",
    "He said it would rain tomorrow.": "主句 `said` 是过去时，从句要「时态往后退」：will 变 `would`。",
    "If I have time, I will go.": "主将从现：if 从句用现在时 `have`，主句用将来时 `will go`。",
  }, {
    neighbor: "名词 n.，邻居，美式拼写；英式写作 neighbour。",
    airport: "名词 n.，机场；到机场用 arrive at the airport。",
    suddenly: "副词 adv.，突然地，常放在句首或动词后。",
    never: "副词 adv.，从不；本身含否定，不要再加 not。",
    journey: "名词 n.，旅程，多指较长的陆路行程；trip 更泛指短途。",
    quiet: "形容词 adj.，安静的；注意和 quite（相当）拼写不同。",
  });

  C("nc3", [
    { t: "there is no doubt that", f: "There is no doubt that + 完整句子", z: "写作高频句式，「毫无疑问……」，that 后面必须是个完整句子。", e: "There is no doubt that he will succeed." },
    { t: "remain 系动词", f: "remain + 形容词 / 名词", z: "remain 表示「仍然是」，后面接形容词，不用 be 动词。", e: "The cause remains unknown." },
    { t: "被动含义的表达", f: "be / remain + 过去分词", z: "主语承受动作时用过去分词，如「原因尚未被查明」。", e: "The cause of the accident remains unknown." },
    { t: "从……中吸取教训", f: "learn a lesson from + 名词", z: "固定搭配，from 后面接教训的来源。", e: "We should learn a lesson from it." },
  ], {
    "The cause of the accident remains unknown.": "`remains` 是系动词，后接形容词 `unknown`；`of the accident` 作后置定语。",
    "The ancient city has a long history.": "`have a long history` 是固定搭配「历史悠久」，history 前加 a。",
    "He remained in silence.": "这里 remain 后接介词短语 `in silence`，表示保持沉默的状态。",
    "We should learn a lesson from it.": "情态动词 `should` 后跟动词原形；`learn a lesson from` 是固定搭配。",
    "The weather affected our plan.": "`affect` 是动词「影响」；名词形式是 effect，别混用。",
    "There is no doubt that he will succeed.": "`There is no doubt that + 句子` 是写作万能句；从句里主语第三人称用 `will succeed`。",
    "This decision has far-reaching effects.": "`far-reaching` 是复合形容词「影响深远的」，修饰名词时要用连字符。",
    "We must take action immediately.": "`must + 动词原形`；`take action` 是固定搭配，action 前不加冠词。",
  }, {
    disaster: "名词 n.，灾难；可数，复数 disasters。",
    ancient: "形容词 adj.，古老的，反义词是 modern。",
    silence: "名词 n.，寂静、沉默；in silence 表示沉默地。",
    doubt: "名词/动词，怀疑；no doubt 表示无疑。",
    succeed: "动词 v.，成功；名词是 success，形容词是 successful。",
    action: "名词 n.，行动；take action 采取行动（不加冠词）。",
  });

  C("primary", [
    { t: "我的 / 你的（物主代词）", f: "my / your / his / her + 名词", z: "这类词后面必须跟名词，表示「谁的」。", e: "This is my school." },
    { t: "can 表示能力", f: "can + 动词原形", z: "「会、能」用 can，后面永远跟动词原形，不加 to。", e: "I can sing." },
    { t: "询问年龄", f: "How old are you?", z: "问年龄的固定句型，回答用 I am + 数字 + years old。", e: "How old are you?" },
    { t: "颜色作名词", f: "like + 颜色", z: "谈论喜欢的颜色时，颜色词直接作名词用，不加 the。", e: "I like red." },
  ], {
    "This is my school.": "`This is` 介绍近处的人或物；`my` 后面必须跟名词。",
    "I like red.": "颜色词在这里作名词用，泛指时不加 the，也不加 s。",
    "He is my good friend.": "`good` 是形容词修饰 `friend`，顺序是「形容词 + 名词」。",
    "We have a cat.": "`We` 后面用 have；第一次提到用 `a cat`。",
    "Good morning, teacher.": "问候语后直接称呼对方，称呼前不加冠词。",
    "This is my pencil.": "结构和 This is my school 一致，替换名词即可。",
    "I can sing.": "`can` 是情态动词，后面跟动词原形，绝不能写 can singing。",
    "How old are you?": "问年龄固定句型；回答 I am nine (years old)。",
  }, {
    school: "名词 n.，学校；上学是 go to school，不加 the。",
    red: "形容词/名词，红色；大写 Red 可作人名。",
    friend: "名词 n.，朋友，可数，复数 friends。",
    pencil: "名词 n.，铅笔，可数；pencil case 是铅笔盒。",
    sing: "动词 v.，唱；过去式 sang，过去分词 sung。",
    happy: "形容词 adj.，开心的；名词是 happiness。",
  });

  C("daily900", [
    { t: "Could you ...? 更礼貌", f: "Could you + 动词原形 + ?", z: "比 Can you 更客气，向陌生人求助时优先用它。", e: "Could you say that again?" },
    { t: "否定转移（I do not think）", f: "I do not think + 肯定句", z: "英文习惯把否定放到前面的 think 上，说「我不认为……」。", e: "I do not think so." },
    { t: "Let us 提议", f: "Let us + 动词原形", z: "邀请对方一起做某事，后面永远跟动词原形。", e: "Let us go." },
    { t: "询问时间", f: "What time is it?", z: "问现在几点的固定说法，回答 It is + 数字 + o'clock。", e: "What time is it now?" },
  ], {
    "Can you help me please?": "求助用 `Can you + 动词原形`；句尾加 `please` 语气更客气。",
    "I am learning English.": "现在进行时 `am learning`，表示这段时间一直在学。",
    "This restaurant is very good.": "主系表结构；`very` 修饰形容词，不能直接修饰动词。",
    "Let us go.": "`Let us` 后跟动词原形，表示「我们……吧」。",
    "What time is it now?": "问时间固定句型；回答用 It is nine o'clock。",
    "Excuse me.": "万能开场白，用于搭话、打断、借过，比 Sorry 更中性。",
    "Sorry, I am late.": "道歉用 Sorry；`I am late` 说明状态，不用 am being。",
    "I do not understand.": "一般现在时否定：`do not + 动词原形`，不要写 I not understand。",
    "Could you say that again?": "`Could you + 动词原形` 是最礼貌的请求句式，比 Can you 更委婉。",
    "Please wait a moment.": "祈使句用动词原形开头；`a moment` 表示一会儿。",
    "I agree.": "agree 是不及物用法，直接说 I agree 即可；同意某人说 I agree with you。",
    "I do not think so.": "英文习惯否定前置：明明是「我认为不」，却说 `I do not think so`。",
    "No problem.": "回应感谢或请求的口语，等于「没问题、小事」。",
    "Thank you so much for your help.": "`Thank you for + 名词/动名词` 是固定搭配，for 后面不能跟动词原形。",
    "You are welcome.": "回应 Thank you 的标准说法；注意是 You are 不是 You are very welcome 也行。",
    "I need some help.": "`help` 不可数，用 `some` 而不是 a；`need` 后直接跟名词。",
    "I really like it here.": "`here` 是副词，放在句尾；`really` 放在动词前加强语气。",
    "See you later.": "告别固定表达，注意是 later 不是 late。",
  }, {
    restaurant: "名词 n.，餐厅，可数，复数 restaurants。",
    help: "名词/动词；作名词不可数，说 some help 不说 a help。",
    time: "名词 n.，时间（不可数）／次数（可数）。",
    understand: "动词 v.，理解；过去式和过去分词都是 understood。",
    moment: "名词 n.，片刻；wait a moment 等一会儿。",
    welcome: "形容词/动词；You are welcome 用于回应感谢。",
    problem: "名词 n.，问题，可数；No problem 是高频口语。",
    again: "副词 adv.，再一次；放在句尾。",
  });

  C("travel", [
    { t: "Would like 想要", f: "would like + 名词 / to do", z: "比 want 更礼貌，点单、提要求时首选。", e: "I would like a window seat." },
    { t: "问路三件套", f: "Where is ...? / How do I get to ...? / Is there ...?", z: "找地方用 Where is，问路线用 How do I get to，问有没有用 Is there。", e: "How do I get to the city center?" },
    { t: "by + 交通/支付方式", f: "by + 交通工具 / 支付方式", z: "by 后面用单数、不加冠词：by credit card、by subway。", e: "Can I pay by credit card?" },
    { t: "too ... to 结构", f: "too + 形容词", z: "too 表示「太……」，含负面意思，比 very 更强调过头。", e: "It is too expensive." },
  ], {
    "I want to go to the airport.": "`want to + 动词原形`；to 是不定式符号，后面不能再加 -ing。",
    "One ticket to Beijing.": "买票口语常省略主谓，用 `One ticket to + 地名`；to 表示目的地。",
    "Where is the restroom?": "问地点用 `Where is`；restroom 比 toilet 更委婉。",
    "How much is this?": "问价格固定句型；回答用 It is + 金额。",
    "Please take a photo for me.": "`take a photo for sb` 表示替某人拍照；`for` 强调为谁做。",
    "What time does my flight leave?": "特殊疑问句需要助动词 `does`，后面动词回原形 `leave`。",
    "Where is the boarding gate?": "`boarding` 是动名词作定语修饰 gate，表示「登机用的门」。",
    "I would like a window seat.": "`would like` 比 want 礼貌；座位类型直接说 window seat / aisle seat。",
    "Is this flight delayed?": "被动含义用过去分词 `delayed` 作形容词，表示「被延误的」。",
    "I booked a room.": "`book` 在这里是动词「预订」，不是名词「书」；过去式加 -ed。",
    "Is breakfast included?": "`be + 过去分词` 构成被动语态，表示「被包含在内」。",
    "Is there free wifi?": "`Is there + 单数名词` 询问是否存在；wifi 不可数。",
    "Is there a supermarket nearby?": "`nearby` 是副词，放句尾；可数与不可数决定用 a 还是直接跟名词。",
    "How do I get to the city center?": "问路线用 `How do I get to + 地点`；get to 表示到达。",
    "Can I pay by credit card?": "`by + 支付方式` 表示用什么付，card 前不加 the，也不用复数。",
    "It is too expensive, can you give me a discount?": "`too + 形容词` 表示「太……了」；砍价固定句是 give me a discount。",
    "I will take this one.": "购物决定时用 `I will take`；`this one` 代替前面提到的物品，避免重复名词。",
    "Where is the subway station please?": "问路结尾加 please 更客气；`subway station` 是复合名词。",
    "Can I get a tax refund here?": "`tax refund` 是退税，固定搭配；get 在这里等于 obtain。",
    "I am lost, can you help me?": "`lost` 是形容词「迷路的」，用 be 动词；两个句子用逗号连接是口语常见写法。",
  }, {
    airport: "名词 n.，机场；去机场用 go to the airport。",
    ticket: "名词 n.，票，可数；一张票是 a ticket。",
    restroom: "名词 n.，洗手间，比 toilet 更礼貌的说法。",
    flight: "名词 n.，航班；take a flight 乘飞机。",
    gate: "名词 n.，登机口、大门；boarding gate 登机口。",
    luggage: "名词 n.，行李，不可数，没有复数；两件行李说 two pieces of luggage。",
    hotel: "名词 n.，酒店，可数；住酒店是 stay at a hotel。",
    breakfast: "名词 n.，早餐；吃早餐是 have breakfast，不加冠词。",
    subway: "名词 n.，地铁（美式）；英式用 underground 或 tube。",
    discount: "名词 n.，折扣；给折扣是 give a discount。",
  });

  C("food", [
    { t: "I would like ... 点单", f: "I would like + 名词 / to do", z: "餐厅点单最常用的礼貌说法，也可缩写成 I would。", e: "I would like a cup of coffee." },
    { t: "Do you have ...? 询问有无", f: "Do you have + 名词?", z: "问餐厅有没有某样东西，比 Is there 更直接问店家。", e: "Do you have a table available?" },
    { t: "make / do 的搭配", f: "make + 食物 / do + 事情", z: "做饭、做辣度用 make，做事用 do。", e: "Please do not make it too spicy." },
    { t: "形容词修饰不定代词后置", f: "something + 形容词", z: "修饰 something、anything 的形容词要放在后面。", e: "Would you like something to drink?" },
  ], {
    "Please give me the menu.": "祈使句；`the menu` 是双方都知道的那份菜单，用 the。",
    "This dish is delicious.": "`delicious` 是形容词作表语；它本身含「非常」的意思，一般不再加 very。",
    "I would like the bill.": "买单就是要账单；美式口语也说 check。",
    "What do you recommend?": "`recommend` 是动词「推荐」；特殊疑问句要用助动词 do。",
    "I would like a cup of coffee.": "`would like` 后接名词；咖啡不可数，一杯要借 `a cup of`。",
    "I would like to reserve a table for two.": "`reserve` 是预订；`for two` 表示两人份。",
    "Do you have a table available?": "`available` 作后置定语，表示「有空位的」，一般放在名词后。",
    "I am allergic to peanuts.": "固定搭配 `be allergic to`；peanut 泛指花生用复数。",
    "Please do not make it too spicy.": "否定祈使句 `do not + 动词原形`；`make it + 形容词` 表示做成什么口味。",
    "Please do not add sugar.": "sugar 不可数，前面不加 a，也不加 s。",
    "Can I get this to go?": "`to go` 是美式「打包带走」，英式说 takeaway。",
    "This dish is too salty.": "`too + 形容词` 表示过头、不满意。",
    "The service was great, thank you.": "`service` 不可数，用 was 不用 were。",
    "Can we have separate bills?": "`separate` 是形容词「分开的」；分账用复数 bills。",
  }, {
    menu: "名词 n.，菜单，可数；看菜单是 read the menu。",
    delicious: "形容词 adj.，美味的，本身很强烈，通常不加 very。",
    bill: "名词 n.，账单；买单说 get the bill。",
    table: "名词 n.，餐桌；订桌是 reserve a table。",
    spicy: "形容词 adj.，辣的；比较级 spicier。",
    salty: "形容词 adj.，咸的；名词是 salt。",
    coffee: "名词 n.，咖啡，不可数；一杯用 a cup of coffee。",
    recommend: "动词 v.，推荐；recommend doing sth 或 recommend sth。",
  });

  C("health", [
    { t: "have a + 病症", f: "have a cold / headache / fever", z: "感冒、头疼这类常见病症前要加 a，是固定搭配。", e: "I have a cold." },
    { t: "动名词作主语", f: "Doing + is + 形容词", z: "动词加 -ing 放句首当主语，谓语用单数 is。", e: "Drinking more water is good for you." },
    { t: "be good for / be good at", f: "be good for + 对象 · be good at + 技能", z: "对……有益用 for，擅长某事用 at。", e: "Drinking more water is good for you." },
    { t: "现在完成进行时", f: "have been + 形容词/动词ing", z: "表示从过去持续到现在，常和 lately 一起出现。", e: "I have been under a lot of stress lately." },
  ], {
    "I need to see a doctor.": "`need to + 动词原形`；看医生是 see a doctor，不是 look a doctor。",
    "Daily exercise is important.": "`exercise` 表示锻炼时不可数；主语是单数概念，谓语用 is。",
    "Keep a healthy diet.": "祈使句；`keep + 名词` 表示保持某种状态，diet 前加 a。",
    "I have a cold.": "`have a cold` 是感冒的固定说法，必须有冠词 a。",
    "Go to bed early.": "`go to bed` 表示上床睡觉，不加 the；early 是副词修饰 go。",
    "I have a headache.": "病症固定搭配 `have a + 病症`，headache 前要加 a。",
    "I need to take medicine.": "`take medicine` 是固定搭配，medicine 不可数，不加 a。",
    "I am allergic to this medication.": "`be allergic to` 对……过敏；medication 是药物的正式说法。",
    "I run for half an hour every day.": "`for + 时间段` 表示持续多久；`every day` 作频率状语。",
    "Drinking more water is good for you.": "动名词 `Drinking` 作主语，谓语用单数 `is`；`be good for` 表示对……有益。",
    "I have been under a lot of stress lately.": "现在完成时 `have been`；`under stress` 是固定搭配，表示承受压力。",
    "Please take a deep breath and relax.": "祈使句；`take a deep breath` 是深呼吸的固定说法，用 take 不用 do。",
  }, {
    doctor: "名词 n.，医生；看医生是 see a doctor。",
    exercise: "名词/动词；作「锻炼」不可数，作「练习题」可数。",
    healthy: "形容词 adj.，健康的；名词是 health。",
    headache: "名词 n.，头痛，可数；have a headache 头痛。",
    medicine: "名词 n.，药，不可数；吃药是 take medicine。",
    stress: "名词 n.，压力，不可数；under stress 处于压力下。",
    water: "名词 n.，水，不可数；一杯水是 a glass of water。",
    sleep: "名词/动词，睡眠；睡觉是 go to sleep。",
  });

  C("cet", [
    { t: "be vital to 至关重要", f: "be + 形容词 + to + 名词", z: "vital、important、essential 后面都接 to，表示对某事物而言。", e: "Education is vital to personal development." },
    { t: "比较级 + than", f: "more + 形容词 / 形容词er + than", z: "两者对比的写作高频结构，注意 more 和 -er 不能同时用。", e: "Health is more important than wealth." },
    { t: "make + 宾语 + 形容词", f: "make + 宾语 + 形容词/动词原形", z: "make 后面接宾语再接形容词，表示使某物变得怎样。", e: "The internet makes communication more convenient." },
    { t: "should + 动词原形", f: "should + 动词原形", z: "表示建议、应当，写作里提出观点常用。", e: "We should protect the environment." },
  ], {
    "Education is vital to personal development.": "`be vital to` 表示对……至关重要；to 是介词，后面跟名词。",
    "We should protect the environment.": "`should + 动词原形`；`the environment` 指整个环境，要加 the。",
    "Technology has changed our way of life.": "现在完成时 `has changed`，强调科技已带来的改变；`way of life` 是固定搭配。",
    "Health is more important than wealth.": "多音节形容词比较级用 `more important`，不能写成 importanter；than 引出比较对象。",
    "Reading can broaden our horizons.": "动名词 `Reading` 作主语，谓语用单数；horizons 表示「眼界」时用复数。",
    "The internet makes communication more convenient.": "`make + 宾语 + 形容词` 结构；communication 不可数，前面不加 a。",
    "We should pay attention to mental health.": "`pay attention to` 是固定搭配，to 是介词，后面跟名词。",
    "Teamwork can improve efficiency.": "`can + 动词原形`；teamwork 与 efficiency 都是不可数名词。",
    "Failure is the mother of success.": "谚语：抽象名词 failure、success 前都不加冠词（success 这里也不加）。",
    "Time management is very important.": "主语 `Time management` 是单数概念，谓语用 is。",
  }, {
    education: "名词 n.，教育，不可数；get an education 受教育。",
    environment: "名词 n.，环境；指自然环境时加 the。",
    technology: "名词 n.，科技，不可数；具体技术可数。",
    internet: "名词 n.，互联网；前面习惯加 the。",
    communication: "名词 n.，沟通，不可数。",
    teamwork: "名词 n.，团队合作，不可数。",
    efficiency: "名词 n.，效率，不可数；形容词是 efficient。",
    failure: "名词 n.，失败；抽象用法不加冠词，具体「一次失败」可加 a。",
  });

  C("kaoyan", [
    { t: "强调句 It is ... that", f: "It is + 被强调部分 + that + 其余", z: "把想强调的成分放到 It is 和 that 之间，写作提分利器。", e: "It is effort that determines the final result." },
    { t: "only + 状语引起倒装", f: "Only + 状语 + 助动词 + 主语 + 动词", z: "Only by doing 放句首时，主句要部分倒装。", e: "Only by cooperation can we solve this problem." },
    { t: "There is no denying that", f: "There is no denying that + 完整句子", z: "「不可否认」的固定句式，用于引出公认事实。", e: "There is no denying that competition is becoming fierce." },
    { t: "Although 与主句", f: "Although + 从句, + 主句", z: "although 表示让步，中文的「虽然……但是」在英文里只能保留一个。", e: "Although it was difficult, he stuck to his goal." },
  ], {
    "Although it was difficult, he stuck to his goal.": "`Although` 引导让步状语从句；英文里 although 和 but 不能同时出现。",
    "It is effort that determines the final result.": "强调句 `It is ... that ...`，强调主语 effort；去掉这两个词句子依然完整。",
    "More and more young people choose to start businesses.": "`more and more` 表示越来越多；`choose to + 动词原形`；start a business 单数时要加 a。",
    "Only by cooperation can we solve this problem.": "`Only + 介词短语` 放句首引起部分倒装：助动词 `can` 提到主语前。",
    "Studies show that sleep affects memory.": "`Studies show that + 从句` 是研究类写作万能句型；affect 是动词，别写成 effect。",
    "There is no denying that competition is becoming fierce.": "`There is no denying that` 引出公认事实；从句用现在进行时表趋势。",
    "This phenomenon deserves further discussion.": "`deserve + 名词` 表示值得；further 是形容词「进一步的」。",
    "Only by constant reflection can we make progress.": "和上一句同结构：only + 状语置首 → 倒装；make progress 不加冠词。",
    "He believes that success comes from persistence.": "`believe that + 从句`；`come from` 表示来源于。",
    "In conclusion, we should view it rationally.": "`In conclusion` 是写作收尾标志词；`view sth as` 也可替换使用。",
  }, {
    cooperation: "名词 n.，合作；in cooperation with 与……合作。",
    memory: "名词 n.，记忆；可数（一段记忆）也可不可数（记忆力）。",
    effort: "名词 n.，努力；make an effort 作出努力（要加 an）。",
    competition: "名词 n.，竞争，可数也可不可数；动词是 compete。",
    phenomenon: "名词 n.，现象；复数是 phenomena，考频高。",
    reflection: "名词 n.，反思、反映；动词是 reflect。",
    persistence: "名词 n.，坚持；形容词 persistent，动词 persist。",
    conclusion: "名词 n.，结论；in conclusion 总而言之，draw a conclusion 得出结论。",
  });

  C("ielts", [
    { t: "have lived for + 时间", f: "have + 过去分词 + for + 时间段", z: "现在完成时 + for，表示从过去持续到现在，这是雅思口语高频。", e: "I have lived in Beijing for five years." },
    { t: "when 引导时间从句", f: "主句 + when + 从句（过去时）", z: "谈论童年经历时，前后都用过去时。", e: "I liked drawing when I was a child." },
    { t: "表达观点", f: "I think + 从句", z: "口语答题先说观点再给理由，是最稳的结构。", e: "I think technology makes life more convenient." },
    { t: "used to / in the future", f: "in the future 表示将来", z: "谈未来计划用 in the future，注意是 in 不是 on。", e: "I want to travel to Europe in the future." },
  ], {
    "My hobby is reading.": "主语和表语要「对等」：hobby 是名词，所以后面用动名词 `reading`，不用 read。",
    "I agree with this opinion.": "`agree with + 人或观点`；`I agree.` 后面不能直接跟 this opinion，要加 with。",
    "Travel broadens the mind.": "不可数名词 `Travel` 作主语，谓语用单数 broadens；mind 表示「心智」单数即可。",
    "I love my hometown.": "`hometown` 是可数名词单数，前面必须有物主代词或冠词。",
    "This city is very safe.": "`safe` 是形容词作表语；`very` 修饰形容词，不能说 very safety。",
    "I have lived in Beijing for five years.": "现在完成时 `have lived` + `for + 时间段`，表示住了五年且现在还在住。",
    "My favorite season is autumn.": "`favorite` 是形容词，前面必须有物主代词；season 是单数。",
    "I usually watch movies with friends.": "`usually` 是频率副词，放在实义动词前；`with friends` 表示和朋友一起。",
    "I think technology makes life more convenient.": "`I think + 从句`；从句里用 `makes + 宾语 + 形容词` 结构。",
    "I liked drawing when I was a child.": "主句用过去式 `liked`，when 从句也用过去式 `was`，时态要一致。",
    "I want to travel to Europe in the future.": "`want to + 动词原形`；表示未来用 `in the future`，不加 the 之外的介词。",
    "This topic is very interesting.": "`interesting` 形容事物本身有趣；如果表达自己感兴趣要用 interested。",
  }, {
    hobby: "名词 n.，爱好，可数，复数 hobbies（y 变 ies）。",
    travel: "名词/动词，旅行；作名词不可数。",
    opinion: "名词 n.，观点；in my opinion 在我看来。",
    season: "名词 n.，季节，可数；四季用定冠词 the。",
    autumn: "名词 n.，秋天；美式也常用 fall。",
    childhood: "名词 n.，童年，不可数；in my childhood 在我的童年。",
    Europe: "专有名词，欧洲，首字母大写，不加 the。",
    convenient: "形容词 adj.，方便的；主语是事物，不说 I am convenient。",
  });

  C("parent", [
    { t: "It is time to ...", f: "It is time to + 动词原形", z: "提醒该做某事了，用 it 作形式主语。", e: "It is time to sleep." },
    { t: "祈使句提醒", f: "动词原形 + 其他", z: "对孩子下指令用祈使句，语气要短促清楚。", e: "Put the toys away." },
    { t: "Let us + 动词原形", f: "Let us + 动词原形", z: "用一起做的方式让孩子配合，比命令更容易接受。", e: "Let us read a book." },
    { t: "动词短语分拆", f: "put ... away / wash ... up", z: "动词 + 副词构成的短语，宾语是代词时必须放中间。", e: "Put the toys away." },
  ], {
    "It is time to sleep.": "`It is time to + 动词原形` 是该做某事了的固定句型，it 是形式主语。",
    "Let us read a book.": "`Let us + 动词原形`；读一本书用 a book，不加 the 除非特指。",
    "Put the toys away.": "`put ... away` 是「收起来」；宾语是名词时放中间或后面都可以。",
    "Are you happy today?": "一般疑问句把 `Are` 提到句首；happy 是形容词作表语。",
    "Mom loves you.": "第三人称单数主语 `Mom` 后的动词加 -s；you 是宾格。",
    "It is time to get up.": "和 It is time to sleep 同结构；`get up` 是起床的固定短语。",
    "Wash your hands and eat.": "两个祈使句用 and 连接，表示先后动作。",
    "Take your time, no rush.": "`Take your time` 是「慢慢来」的固定说法；no rush 进一步安抚。",
    "Well done!": "表扬固定用语；正式写作里用 Well done 而不是 Good job 更中性。",
    "Please be careful.": "祈使句用 be 加形容词；`careful` 是形容词，不能换成 carefully。",
  }, {
    sleep: "名词/动词，睡觉；go to sleep 入睡。",
    toy: "名词 n.，玩具，可数，复数 toys。",
    happy: "形容词 adj.，开心的；反义词 sad。",
    hands: "名词 n.，手，复数；洗手是 wash your hands，要用复数。",
    dinner: "名词 n.，晚餐；吃晚餐是 have dinner，不加冠词。",
    careful: "形容词 adj.，小心的；副词形式是 carefully。",
  });

  C("kids", [
    { t: "a / an 的选择", f: "an + 元音音素开头的词", z: "看的是读音不是字母：an apple，但 a university。", e: "This is an apple." },
    { t: "Let us + 动词", f: "Let us + 动词原形", z: "邀请一起做某事，后面永远跟原形。", e: "Let us go and play." },
    { t: "can 表能力", f: "can + 动词原形", z: "「会做某事」用 can，后面直接跟动词。", e: "I can count to ten." },
    { t: "现在进行时", f: "is / are + 动词ing", z: "描述眼前正在发生的画面，绘本里最常见。", e: "The bird is flying." },
  ], {
    "I have a small dog.": "先形容词 `small` 再名词 `dog`，顺序不能颠倒。",
    "The sky is blue.": "世界上独一无二的事物前加 `the`，如 the sky、the sun。",
    "I love my mom.": "`my` 是物主代词，后面必须跟名词；称呼亲人一般不大写（句首除外）。",
    "This is an apple.": "`apple` 以元音音素开头，冠词要用 `an` 而不是 a。",
    "Let us go and play.": "`Let us + 动词原形`；go and play 用 and 连接两个动作。",
    "I can count to ten.": "`can + 动词原形`；`count to + 数字` 表示数到几。",
    "The bird is flying.": "现在进行时 `is flying`，描述此刻正在飞。",
    "It is hot today.": "描述天气用 `It is + 形容词`，it 指代天气。",
    "I like ice cream.": "`ice cream` 作物质名词不可数，前面不加 a。",
    "Goodbye, see you tomorrow.": "告别固定表达；`see you + 时间` 表示到时候见。",
  }, {
    apple: "名词 n.，苹果；元音前用 an apple。",
    blue: "形容词/名词，蓝色；the sky is blue 天空是蓝的。",
    dog: "名词 n.，狗，可数，复数 dogs。",
    count: "动词 v.，数数；count to ten 数到十。",
    bird: "名词 n.，鸟，可数，复数 birds。",
    "ice cream": "名词短语，冰淇淋；作物质名词不可数。",
  });

  C("biz", [
    { t: "look forward to", f: "look forward to + 名词 / 动词ing", z: "邮件结尾必备；to 是介词，后面必须跟 -ing 或名词。", e: "I look forward to your reply." },
    { t: "I am writing to ...", f: "I am writing to + 动词原形", z: "邮件开门见山的固定开头，说明写这封信的目的。", e: "I am writing to inquire about this." },
    { t: "please feel free to", f: "please feel free to + 动词原形", z: "礼貌地邀请对方随时联系，商务邮件高频。", e: "Please feel free to contact me with any questions." },
    { t: "as soon as possible", f: "as ... as possible", z: "「尽可能……」的固定结构，中间放形容词或副词。", e: "We will handle it as soon as possible." },
  ], {
    "Please find the attachment.": "邮件固定句：`Please find + 名词` 表示「请查收」；附件也可说 the attached file。",
    "I look forward to your reply.": "`look forward to` 中 to 是介词，后面接名词或 -ing，绝不能跟动词原形。",
    "Could we schedule a meeting?": "`Could we + 动词原形` 是委婉提议；schedule 作动词是「安排」。",
    "Thank you for your time.": "`Thank you for + 名词`；time 在这里不可数，不加 s。",
    "It is a pleasure to work with you.": "`It is a pleasure to + 动词原形` 是客套表达；work with 表示共事。",
    "I am writing to inquire about this.": "`I am writing to + 动词原形` 说明写信目的；inquire about 是询问。",
    "Please let me know your decision.": "`let me know` 是「告知我」，后面直接跟内容，不加 about。",
    "Please find the quotation attached.": "`attached` 是过去分词作后置定语，修饰 quotation，等于「随信附上的」。",
    "Please feel free to contact me with any questions.": "`feel free to + 动词原形` 表示随时可以；`with any questions` 说明事由。",
    "I apologize for the late reply.": "`apologize for + 名词`；late 作形容词修饰 reply 表示迟到的回复。",
    "I would like to confirm the details.": "`would like to + 动词原形` 比 want 客气得多；details 常用复数。",
    "Please forward this email to the relevant people.": "`forward sth to sb` 表示转发给某人；relevant 是「相关的」。",
    "We will handle it as soon as possible.": "`handle` 是处理；`as soon as possible` 是尽可能快的固定说法。",
    "Here is the updated proposal.": "`Here is + 单数名词` 倒装句型；`updated` 是过去分词作定语表示已更新的。",
    "Thank you for your patience and cooperation.": "`Thank you for + 名词`；patience、cooperation 都不可数。",
    "Best regards.": "邮件结尾敬语，`regards` 固定用复数，前面可加 Best / Kind。",
  }, {
    attachment: "名词 n.，附件；attach 是动词「附上」。",
    reply: "名词/动词，回复；in reply to 作为对……的回复。",
    meeting: "名词 n.，会议；开会是 hold a meeting。",
    quotation: "名词 n.，报价单；quote 是动词「报价」。",
    decision: "名词 n.，决定；make a decision 作决定。",
    details: "名词 n.，细节，常用复数；in detail 详细地。",
    proposal: "名词 n.，方案、提案；动词是 propose。",
    regards: "名词 n.，问候，固定用复数，用于邮件结尾。",
    confirm: "动词 v.，确认；名词是 confirmation。",
    apologize: "动词 v.，道歉；apologize to sb for sth。",
  });

  C("meeting", [
    { t: "Let us 开场", f: "Let us + 动词原形", z: "主持会议的开场句，后面永远跟原形。", e: "Let us start the meeting." },
    { t: "用 I will 表态", f: "I will + 动词原形", z: "主动认领任务时说 I will，比 I can 更有承诺感。", e: "I will report the progress." },
    { t: "礼貌表达不同意见", f: "I see it differently.", z: "比 I disagree 更缓和，会议里更专业。", e: "I see it differently." },
    { t: "被动语态安排日程", f: "be scheduled for + 时间", z: "会议被安排在某个时间，用被动语态。", e: "The next meeting is scheduled for Friday." },
  ], {
    "Let us start the meeting.": "`Let us + 动词原形` 用于提议开始；meeting 前加 the 表示这场会。",
    "Please review the agenda.": "祈使句；`agenda` 是议程，会议里固定说法。",
    "We need a deadline.": "`deadline` 是可数名词单数，前面要加 a。",
    "I will report the progress.": "`will + 动词原形` 表示主动承担；progress 不可数，不加 a。",
    "Thank you all for joining.": "`Thank you all for + 动名词`；join 在这里不加宾语表示「参与」。",
    "We will discuss three items today.": "`discuss` 是及物动词，后面直接跟宾语，不加 about。",
    "Let me give you some background first.": "`Let me + 动词原形`；`give sb sth` 是双宾结构。",
    "Any comments?": "口语省略句，完整是 Do you have any comments；comments 用复数。",
    "I agree with you.": "`agree with + 人`；如果同意的是方案，用 agree to the plan。",
    "I see it differently.": "用 `differently` 副词修饰 see，这句话是会议里最体面的反对。",
    "Let us get back on track.": "`get back on track` 是回到正题的固定习语。",
    "This plan is too risky.": "`too + 形容词` 表示过于；risky 是形容词作表语。",
    "We need more data to support it.": "`data` 不可数，用 more 不用 many；`to support it` 是目的状语。",
    "Please summarize the conclusions.": "祈使句；`summarize` 是动词总结，conclusions 用复数表示多条结论。",
    "The next meeting is scheduled for Friday.": "`be scheduled for + 时间` 是安排在某时的被动结构。",
    "Please send the meeting notes to everyone.": "`send sth to sb` 结构；`meeting notes` 指会议纪要。",
  }, {
    agenda: "名词 n.，议程，可数；on the agenda 在议程上。",
    deadline: "名词 n.，截止时间；meet the deadline 赶上截止期。",
    report: "名词/动词，报告；作动词是汇报。",
    background: "名词 n.，背景，不可数；background information 背景资料。",
    comment: "名词 n.，评论、意见，可数；No comment 无可奉告。",
    risky: "形容词 adj.，有风险的；名词是 risk。",
    data: "名词 n.，数据，不可数；常用复数动词也可用单数。",
    summarize: "动词 v.，总结；名词是 summary。",
    notes: "名词 n.，笔记、纪要，常用复数；take notes 记笔记。",
    scheduled: "动词过去分词/形容词，已安排的；be scheduled for。",
  });

  C("job", [
    { t: "be in charge of", f: "be in charge of + 名词 / 动词ing", z: "表示负责某事，面试讲职责必备。", e: "I was in charge of managing client accounts." },
    { t: "be familiar with", f: "be familiar with + 名词", z: "表示熟悉某事；主语是人时用 with。", e: "I am familiar with this industry." },
    { t: "用过去时讲经历", f: "I + 动词过去式", z: "讲上一份工作的经历要用过去时。", e: "I majored in marketing." },
    { t: "would like to know", f: "Could you tell me ...?", z: "面试反问环节，用疑问句把问题抛回去。", e: "What are the daily responsibilities of this role?" },
  ], {
    "I have a lot of relevant experience.": "`a lot of` 后接不可数名词 experience；experience 指经验时不可数。",
    "My strength is being careful.": "主语 strength 后跟动名词 `being`，因为表语要和主语对等。",
    "I am flexible about salary.": "`be flexible about` 表示在某事上灵活；salary 是可数名词。",
    "Why do you want to join us?": "特殊疑问句用助动词 `do`；`want to + 动词原形`。",
    "I can start next week.": "`can + 动词原形`；next week 作时间状语，前面不加介词。",
    "I graduated from Peking University.": "`graduate from + 学校` 是固定搭配，不能用 graduate in。",
    "I majored in marketing.": "`major in + 专业` 是固定搭配；majored 用过去式讲学历。",
    "I was in charge of managing client accounts.": "`be in charge of + 动词ing`；accounts 用复数表示多个客户账户。",
    "I helped the company increase sales by twenty percent.": "`help sb do sth` 后面不加 to；`by + 百分比` 表示提升了多少。",
    "I am familiar with this industry.": "`be familiar with + 名词`，主语是人；反过来事物熟悉某人要用 be familiar to。",
    "I left because the company relocated.": "`because + 从句` 给理由；relocated 用过去式，和 left 时态一致。",
    "I want to grow on a bigger platform.": "`want to + 动词原形`；`on a platform` 用介词 on 表示在平台上。",
    "My biggest strength is learning fast.": "形容词最高级 `biggest` 前加 my；表语用动名词 learning 与主语对等。",
    "I sometimes try to be too perfect.": "`try to + 动词原形`；`too + 形容词` 含负面意味，用来做缺点很自然。",
    "I want to become a team leader within five years.": "`within + 时间段` 表示在某段时间内；a team leader 前加 a。",
    "My expected salary is fifteen thousand per month.": "`per month` 表示每月；期望值说 expected salary。",
    "What are the daily responsibilities of this role?": "`responsibilities` 用复数；`of this role` 作后置定语。",
    "How many people are on the team now?": "`How many + 复数名词`；`on the team` 表示是团队成员。",
    "I have a few questions to confirm.": "`a few + 可数名词复数`；`to confirm` 是不定式作定语修饰 questions。",
    "It was a pleasure talking with you today.": "`It was a pleasure + 动词ing` 是面试结尾的客套话。",
  }, {
    experience: "名词 n.，经验（不可数）／经历（可数）。",
    salary: "名词 n.，薪资，可数；expected salary 期望薪资。",
    strength: "名词 n.，优势、强项；复数是 strengths。",
    graduate: "动词 v.，毕业；graduate from + 学校。",
    major: "动词 v.，主修；也可作名词表示专业。",
    industry: "名词 n.，行业，可数；复数 industries。",
    responsible: "形容词 adj.，负责的；be responsible for 对……负责。",
    opportunity: "名词 n.，机会，可数；a good opportunity 好机会。",
    relocate: "动词 v.，搬迁；名词是 relocation。",
    platform: "名词 n.，平台；on a bigger platform 在更大的平台。",
  });

  C("negotiation", [
    { t: "prefer 的用法", f: "prefer + 名词 / prefer A to B / prefer to do", z: "表示更倾向，注意它有三种搭配，后面不接 -ing 时用 to do。", e: "We prefer payment by installments." },
    { t: "cannot compromise on", f: "cannot + 动词 + on + 名词", z: "compromise、agree、insist 后面跟 on 再接事情。", e: "We cannot compromise on this point." },
    { t: "条件句谈判", f: "If + 现在时, + 主句将来时", z: "谈条件时用主将从现：如果达成一致，今天就签。", e: "If we agree, we will sign today." },
    { t: "look forward to 结尾", f: "look forward to + 名词", z: "谈判收尾的客气话；to 是介词，后面接名词或 -ing。", e: "I look forward to a smooth cooperation." },
  ], {
    "We can offer a discount.": "`can + 动词原形`；`offer sb sth` 也可说 offer a discount to you。",
    "Let us sign the contract.": "`Let us + 动词原形`；签合同是 sign the contract，动词用 sign 不用 write。",
    "We reached an agreement.": "`reach an agreement` 是达成协议的固定搭配；agreement 前加 an。",
    "The price is negotiable.": "`negotiable` 是形容词「可商量的」，作表语；动词是 negotiate。",
    "This is our final offer.": "`final` 强调最终的，谈判里表态用；offer 是可数名词。",
    "This price is beyond our budget.": "`beyond + 名词` 表示超出；budget 在这里可数也可不可数。",
    "Can we meet in the middle?": "`meet in the middle` 是各让一步的习语，不是真的见面。",
    "Can we get a better price for a bulk order?": "`a better price` 用比较级；`for + 订单` 说明针对什么。",
    "We prefer payment by installments.": "`prefer + 名词`；`by installments` 表示分期付款。",
    "Let us go over the terms again.": "`go over` 是「过一遍、检查」；terms 用复数指合同条款。",
    "We cannot compromise on this point.": "`cannot compromise on + 事情` 是「绝不在这点上让步」的强硬表态。",
    "We need written confirmation.": "`written` 是过去分词作形容词修饰 confirmation，表示书面的。",
    "If we agree, we will sign today.": "主将从现：if 从句用 `agree` 现在时，主句用 `will sign`。",
    "I look forward to a smooth cooperation.": "`look forward to + 名词`；to 是介词，后面接名词或 -ing，不接原形。",
  }, {
    discount: "名词 n.，折扣；给折扣是 offer a discount。",
    contract: "名词 n.，合同；签合同是 sign a contract。",
    agreement: "名词 n.，协议；reach an agreement 达成协议。",
    budget: "名词 n.，预算；over budget 超预算。",
    terms: "名词 n.，条款，常用复数；terms and conditions 条款细则。",
    installment: "名词 n.，分期付款；by installments 分期地。",
    compromise: "动词/名词，妥协；compromise on sth 在某事上让步。",
    confirmation: "名词 n.，确认；written confirmation 书面确认。",
    bulk: "名词/形容词，大批；bulk order 批量订单。",
    smooth: "形容词 adj.，顺利的、平滑的；smooth cooperation 顺利的合作。",
  });

  C("movie", [
    { t: "现在完成时口语", f: "I have had enough.", z: "have + 过去分词，表示「到目前已经够了」，是高频口语。", e: "I have had enough." },
    { t: "It is none of your business", f: "It is none of + 物主代词 + business", z: "「不关你的事」，注意 business 前用物主代词。", e: "It is none of your business." },
    { t: "will be right back", f: "will + 动词原形", z: "马上回来，口语常用 be right back。", e: "I will be right back." },
    { t: "let / leave 的区别", f: "leave sb alone", z: "「别管我」用 leave，不是 let；let 是「让」。", e: "Leave me alone." },
  ], {
    "That is awesome!": "`awesome` 是口语里最高的赞美之一，比 good 强烈得多。",
    "Do you really think so?": "一般疑问句用助动词 `Do` 开头；`think so` 代替前面说过的内容。",
    "We are good friends.": "`good friends` 用复数，因为主语是 we，表示一类人。",
    "Do not worry.": "否定祈使句 `do not + 动词原形`，口语里常缩读。",
    "See you tomorrow.": "告别固定表达；tomorrow 作状语不加介词。",
    "Are you kidding me?": "现在进行时表当下的反应，kidding（开玩笑）是固定口语用法。",
    "Come on.": "万能口语，可表示催促、不信、鼓励，靠语气分辨意思。",
    "I have had enough.": "现在完成时 `have had`，表示到此为止、受够了。",
    "It is none of your business.": "固定句型 `It is none of your business`，business 前必须用物主代词。",
    "You are right about that.": "`be right about + 某事` 表示在……上说得对。",
    "I have no idea.": "`have no idea` 等于 I do not know，但更口语、语气更强。",
    "I will be right back.": "`will + be`；`right back` 表示马上就回来。",
    "I guess so.": "`I guess so` 表示不太确定的同意；否定是 I guess not。",
    "Suit yourself.": "字面「随你方便」，实际语气略冷淡，表示「随便你」。",
    "I think we should get going.": "`should + 动词原形` 提建议；`get going` 是出发、走人。",
    "What is the point of this?": "`What is the point of + 名词/动词ing` 表示这有什么意义。",
    "Leave me alone.": "`leave sb alone` 是别打扰某人的固定搭配，不能用 let。",
    "I did not mean it.": "`mean` 是「有意」，过去式否定 `did not mean` 表示我不是故意的。",
    "After you.": "进门、上电梯时的礼让用语，字面「在你之后」。",
    "It has been a long time.": "现在完成时 `has been`，表示「从过去到现在很久没见了」。",
  }, {
    awesome: "形容词 adj.，极好的，口语频率极高。",
    really: "副词 adv.，真的；放在动词或形容词前加强语气。",
    friend: "名词 n.，朋友，可数，复数 friends。",
    kidding: "动词 kid 的现在分词，口语里表示「开玩笑」。",
    idea: "名词 n.，主意、想法，可数；have no idea 不知道。",
    guess: "动词/名词，猜；I guess so 我想是吧。",
    alone: "形容词/副词，独自的；leave me alone 别管我。",
    mean: "动词 v.，意思、有意；过去式 meant。",
    point: "名词 n.，要点、意义；the point of 的重点。",
    enough: "形容词/副词，足够的；放在名词前、形容词后。",
  });

  C("idiom", [
    { t: "习语要与主语搭配", f: "主语 + 动词 + 习惯搭配", z: "习语是整体记忆单位，改主语时动词形式仍要跟主语变。", e: "He drives me crazy." },
    { t: "祈使句 + 提醒", f: "动词原形开头", z: "Watch out、Take it easy 都是祈使句，省略了主语。", e: "Watch out, it is going to rain." },
    { t: "be going to 表预测", f: "be going to + 动词原形", z: "根据眼前迹象推测要发生的事，用 be going to。", e: "Watch out, it is going to rain." },
    { t: "let us 建议", f: "Let us + 动词原形", z: "提出建议、招呼大家一起做某事。", e: "Let us get back to business." },
  ], {
    "It is a piece of cake.": "习语 `a piece of cake` 表示小菜一碟，这里的 cake 不指真的蛋糕。",
    "Watch out, it is going to rain.": "`Watch out` 是祈使句提醒当心；`be going to` 表示根据迹象的推测。",
    "He drives me crazy.": "主语是第三人称单数 `He`，动词 drive 要加 `-s`；`drive sb crazy` 是使人抓狂。",
    "Let us get back to business.": "`get back to business` 表示言归正传，business 前不加 the。",
    "I get what you mean.": "这里的 `get` 是口语「理解」；`what you mean` 是宾语从句。",
    "Take it easy.": "祈使句固定用语，表示别紧张、放轻松；it 是形式宾语。",
    "This is a golden opportunity.": "`golden` 是形容词「黄金般的」；opportunity 可数，前面加 a。",
    "He is a big shot.": "`a big shot` 是「大人物」的习语，shot 在这里不指射击。",
    "We are even.": "`be even` 表示互不相欠、扯平，体育里也表示比分相同。",
    "It is a long story.": "`a long story` 表示说来话长，常配合省略原因使用。",
    "Do not spill the beans.": "习语 `spill the beans` 是泄露秘密；否定祈使用 do not 开头。",
    "He got cold feet.": "`get cold feet` 是临阵退缩，注意用复数 feet。",
    "We are on the same page.": "`be on the same page` 表示想法一致，page 前要加 the。",
    "Do not make a mountain out of a molehill.": "习语：把鼹鼠丘说成大山，即小题大做；两个名词前都用 a。",
    "Let us wait and see.": "`wait and see` 用 and 连接两个动词原形，表示观望。",
    "It is a good deal.": "`deal` 在这里指交易；a good deal 表示很划算。",
    "He means business.": "`mean business` 表示是认真的，不是开玩笑。",
    "Patience is a virtue.": "抽象名词 `Patience` 作主语，谓语用单数 is；a virtue 前加 a。",
  }, {
    piece: "名词 n.，片、块；a piece of 用于不可数名词计量。",
    cake: "名词 n.，蛋糕；可数也可不可数，a piece of cake 也可表示小菜一碟。",
    rain: "名词/动词，雨；不可数，heavy rain 大雨。",
    opportunity: "名词 n.，机会，可数；a golden opportunity 绝佳机会。",
    secret: "名词 n.，秘密，可数；keep a secret 保守秘密。",
    story: "名词 n.，故事；a long story 说来话长。",
    deal: "名词 n.，交易；a good deal 划算的交易。",
    beans: "名词 n.，豆子，常用复数；spill the beans 泄密。",
    patient: "形容词 adj.，有耐心的；名词是 patience。",
    serious: "形容词 adj.，认真的、严肃的；副词 seriously。",
  });

  C("tech", [
    { t: "被动语态描述系统状态", f: "be + 过去分词", z: "系统被维护、被部署，用被动语态最自然。", e: "The system is under maintenance." },
    { t: "put ... into production", f: "put + 宾语 + into + 名词", z: "发布到生产环境的固定说法，宾语夹在中间。", e: "We will put it into production." },
    { t: "There is ... to do", f: "There is + 名词 + to 动词原形", z: "表示「有一个……要处理」，to do 作后置定语。", e: "There is a bug to fix." },
    { t: "not ... yet", f: "be not + 过去分词 + yet", z: "「还没」用 yet，放在否定句末尾。", e: "This feature is not finished yet." },
  ], {
    "I will write this code.": "`will + 动词原形` 表示主动认领任务；code 作「代码」不可数。",
    "We deployed a new version.": "`deployed` 是过去式；version 可数，前面加 a。",
    "There is a bug to fix.": "`There is + 名词 + to do` 表示有某事要做；bug 前加 a。",
    "Please submit your proposal.": "祈使句；`submit` 是提交，proposal 是可数名词。",
    "The system is under maintenance.": "`under maintenance` 是固定搭配，表示处于维护状态，不用 being maintained 更自然。",
    "I need to review this code.": "`need to + 动词原形`；review 在这里是审查，不是复习。",
    "This feature is not finished yet.": "`not ... yet` 表示还没完成；finished 是过去分词作形容词。",
    "We will put it into production.": "`put sth into production` 是固定说法；代词 it 放在 put 和 into 之间。",
    "The server is down.": "`be down` 表示服务不可用；down 是形容词作表语。",
    "Please open a ticket.": "IT 里的 ticket 指工单；`open a ticket` 是提工单。",
    "We need a technical solution.": "`technical` 是形容词修饰 solution；solution 可数，前面加 a。",
    "The API returned an error.": "`returned` 过去式；API 首字母缩写读作字母，前面加 the。",
  }, {
    code: "名词 n.，代码，不可数；写代码是 write code。",
    deploy: "动词 v.，部署；名词是 deployment。",
    bug: "名词 n.，漏洞、缺陷，可数；fix a bug 修 bug。",
    server: "名词 n.，服务器，可数。",
    feature: "名词 n.，功能，可数；复数 features。",
    review: "动词/名词，审查、评审；code review 代码评审。",
    production: "名词 n.，生产环境；in production 在生产环境。",
    solution: "名词 n.，方案，可数；a solution to 某问题的方案。",
  });

  C("travelpro", [
    { t: "I would like to ... 出门万能句", f: "I would like to + 动词原形", z: "比 I want to 礼貌，机场、酒店、餐厅提要求都用它。", e: "I would like to check in for my flight." },
    { t: "for + 时间段", f: "will stay for + 时间段", z: "表示会待多久，for 后面接时间长度。", e: "I will stay for seven days." },
    { t: "How long does it take?", f: "How long does it take to + 地点？", z: "问到某地要多久的固定句型，take 后跟时间。", e: "How long does it take to the airport?" },
    { t: "There is no + 名词", f: "There is no + 不可数/单数名词", z: "表示某处没有某物，no 后面直接跟名词。", e: "There is no hot water in the room." },
    { t: "have nothing to + 动词", f: "have nothing to do / declare", z: "「没有什么要……」，不定式作后置定语。", e: "I have nothing to declare." },
  ], {
    "I would like to check in for my flight.": "`would like to + 动词原形` 是最礼貌的表达；`check in for a flight` 是办理登机手续。",
    "I need to check in this luggage.": "`need to + 动词原形`；luggage 不可数，用 this 而不是 these。",
    "Can I carry this on board?": "`Can I + 动词原形` 请求许可；`on board` 表示登机、上船后。",
    "My seat is by the window.": "`by + 名词` 表示在……旁边；靠窗座位也说 a window seat。",
    "I am here on vacation.": "`on vacation` 是固定搭配，表示在度假，不能换成 in vacation。",
    "I will stay for seven days.": "`will + 动词原形`；`for + 时间段` 表示持续多久。",
    "This is my first time here.": "`This is my first time + 地点` 是固定说法；here 是副词，前面不加介词。",
    "Where is customs please?": "`customs` 指海关，固定用复数形式；问路句尾加 please 更客气。",
    "I have nothing to declare.": "`nothing to + 动词原形` 表示没有要做的；declare 是申报，报关行常用。",
    "I have a reservation.": "`have a reservation` 表示已有预订；reservation 可数，前面加 a。",
    "Could I have my room key?": "`Could I have + 名词` 比 Can I 更客气；key 用单数指自己房间那把。",
    "There is no hot water in the room.": "`There is no + 不可数名词`；water 不可数，前面不加 a。",
    "I would like to change my room.": "`would like to + 动词原形`；换房说 change my room。",
    "I am checking out tomorrow.": "现在进行时表将来安排，`check out` 是退房，和 check in 相对。",
    "How do I get to the subway station?": "问路固定句型 `How do I get to + 地点`；get to 表示到达。",
    "How long does it take to the airport?": "`How long does it take to + 地点` 问到某地要多久；take 表示花费时间。",
    "Please take me to this address.": "`take sb to + 地点` 是带某人去某地；`this address` 用 this 指手上的地址。",
    "Is there a pharmacy nearby?": "`Is there + 可数名词单数` 询问有没有；nearby 是副词放句尾。",
    "Can I get a tax refund?": "`tax refund` 是退税，固定搭配；get 在这里等于 obtain。",
    "I lost my wallet.": "`lost` 是过去式，讲述已经发生的事；wallet 可数，前面加物主代词。",
  }, {
    passport: "名词 n.，护照，可数；出示护照是 show your passport。",
    customs: "名词 n.，海关，固定用复数；go through customs 过海关。",
    declare: "动词 v.，申报；nothing to declare 无可申报。",
    reservation: "名词 n.，预订，可数；make a reservation 预订。",
    check: "动词/名词，检查；check in 办理登记，check out 退房。",
    refund: "名词 n.，退款；tax refund 退税，动词也写作 refund。",
    wallet: "名词 n.，钱包，可数；注意和 purse（女用钱包）区分。",
    pharmacy: "名词 n.，药房；美式也可说 drugstore。",
    address: "名词 n.，地址，可数；问地址是 What is your address。",
    emergency: "名词 n.，紧急情况；in an emergency 在紧急情况下。",
  });

  C("interview", [
    { t: "用完成时讲经验", f: "have + 过去分词 + for + 时间", z: "讲累积经验用现在完成时，比一般过去时更显得经验持续。", e: "I have eight years of experience in this field." },
    { t: "讲成就用过去时", f: "My greatest achievement was + 名词/动词ing", z: "讲某一次成就用过去时，表语要和主语对等。", e: "My greatest achievement was completing that transformation." },
    { t: "be a good fit for", f: "be a good fit for + 岗位", z: "「适合这个岗位」的地道说法，比 suitable 更常用。", e: "Why am I a good fit for this role?" },
    { t: "Why 引导的自问自答", f: "Why am I ...? 常用于面试话术", z: "面试中常把问题内化自答，先说问题再给答案。", e: "Why am I a good fit for this role?" },
  ], {
    "Let me briefly introduce myself.": "`Let me + 动词原形`；briefly 是副词，修饰 introduce。",
    "I have eight years of experience in this field.": "现在完成时 `have` 表示经验累积至今；`in this field` 用介词 in。",
    "My previous role was project manager.": "表语是职位名称，前面可以不加冠词；`previous` 表示上一份。",
    "I led a team of ten people.": "`led` 是 lead 的过去式（不规则）；`a team of + 数字` 表示多大团队。",
    "My greatest achievement was completing that transformation.": "表语用动名词 `completing`，和主语 achievement 对等；最高级前加 my。",
    "I left to look for new challenges.": "`to look for` 是不定式作目的状语，说明离职原因；challenges 用复数。",
    "My strength is working well under pressure.": "表语用动名词 `working`；`under pressure` 表示在压力之下。",
    "My weakness is that I sometimes focus too much on details.": "表语是 that 引导的从句；`focus on` 是固定搭配。",
    "I am working on improving that.": "现在进行时表示正在做；`work on + 动词ing` 表示致力于改进。",
    "I once handled a team conflict.": "`once` 表示曾经；handled 用过去式讲过去的一次经历。",
    "I tend to listen first and then decide.": "`tend to + 动词原形` 表示倾向于；first and then 表示先后顺序。",
    "Why am I a good fit for this role?": "`be a good fit for + 职位` 是「适合这个岗位」的地道说法。",
    "I really admire your company culture.": "`admire` 是欣赏；company culture 前面用物主代词 your。",
    "I value growth opportunities more.": "`value` 作动词表示重视；more 放句尾表示相比之下更看重。",
    "Is this position open to remote work?": "`be open to + 名词` 表示对某事开放；remote work 指远程办公。",
    "My notice period is two weeks.": "`notice period` 是离职通知期，外企高频词。",
    "Could you tell me about the team?": "`Could you tell me about + 名词` 是礼貌提问句式。",
    "What does the career path for this role look like?": "`What does ... look like` 问……是什么样；career path 是职业发展路径。",
    "What are the next steps?": "`next steps` 用复数指接下来的流程；面试结尾常用。",
    "Thank you for your time and I look forward to hearing from you.": "`Thank you for + 名词`；`look forward to + 动词ing`，to 是介词所以用 hearing。",
  }, {
    briefly: "副词 adv.，简要地；修饰动词，如 introduce briefly。",
    achievement: "名词 n.，成就，可数；achieve 是动词。",
    conflict: "名词 n.，冲突，可数；team conflict 团队冲突。",
    pressure: "名词 n.，压力，不可数；under pressure 在压力下。",
    weakness: "名词 n.，缺点，可数；复数 weaknesses。",
    culture: "名词 n.，文化；company culture 企业文化。",
    candidate: "名词 n.，候选人、应聘者，可数。",
    promotion: "名词 n.，晋升；get a promotion 升职。",
    remote: "形容词 adj.，远程的；remote work 远程办公。",
    notice: "名词 n.，通知期；notice period 离职通知期。",
  });

  C("biztalk", [
    { t: "I am calling to ...", f: "I am calling to + 动词原形", z: "电话开场说明来意，比 I want to 更专业。", e: "I am calling to follow up." },
    { t: "用过去分词道歉升级", f: "I am afraid + 从句", z: "要说坏消息时，用 I am afraid 先铺垫，语气更委婉。", e: "I am afraid we have to delay the delivery." },
    { t: "have to + 动词原形", f: "have to / has to", z: "表示客观不得不，比 must 更常用于商务场合。", e: "I am afraid we have to delay the delivery." },
    { t: "we could 提议", f: "We could + 动词原形", z: "提出可行方案时用 could，比 should 更留余地。", e: "We could start with a pilot." },
  ], {
    "I am calling to follow up.": "`I am calling to + 动词原形` 说明打电话的目的；follow up 是跟进。",
    "Could we move the meeting earlier?": "`Could we + 动词原形` 是委婉提议；earlier 是比较级作补语。",
    "I have a bad connection on my end.": "`on my end` 表示我这边，电话沟通专用说法。",
    "Could you repeat that please?": "`Could you + 动词原形` 最礼貌；repeat 是及物动词，that 指前面的话。",
    "Let me confirm the key points.": "`Let me + 动词原形`；`key points` 用复数指多个要点。",
    "We have reached a consensus.": "现在完成时 `have reached` 强调已达成；consensus 是共识，不可数。",
    "I understand your concern.": "`concern` 是可数名词表示顾虑，用 your 修饰更显共情。",
    "Let me put it another way.": "`put it another way` 是换种说法的固定表达，it 指前面的事。",
    "We could start with a pilot.": "`could + 动词原形` 表示可能的方案；`start with` 表示先从……开始。",
    "I will take care of this issue.": "`take care of` 是处理、负责；`will` 表示承诺。",
    "I am afraid we have to delay the delivery.": "`I am afraid` 是委婉说坏消息的开头；`have to` 表示客观不得不。",
    "We will cover the loss this time.": "`cover the loss` 是承担损失；`this time` 表示这一次。",
    "We apologize for the inconvenience.": "`apologize for + 名词`；inconvenience 是正式场合的道歉用语。",
    "Thank you for your understanding and patience.": "`Thank you for + 名词`；两个名词都不可数，不加 s。",
    "I hope we can continue our cooperation.": "`hope + 从句` 表示期望；continue 后直接跟宾语，不加 to。",
    "Please send me the contract for confirmation.": "`send sb sth` 是双宾结构；`for confirmation` 表示为了确认。",
    "We are confident about this partnership.": "`be confident about + 名词` 表示对某事有信心。",
    "We look forward to a long-term mutually beneficial relationship.": "`look forward to + 名词`；`long-term` 是复合形容词，常用连字符。",
  }, {
    follow: "动词 v.，跟随、跟进；follow up 跟进。",
    consensus: "名词 n.，共识，不可数；reach a consensus 达成共识。",
    concern: "名词 n.，顾虑、关切，可数；动词是 concern。",
    pilot: "名词 n.，试点、试运行；a pilot project 试点项目。",
    delay: "动词/名词，延期；delay the delivery 延期交付。",
    loss: "名词 n.，损失，可数；cover the loss 承担损失。",
    apologize: "动词 v.，道歉；apologize for sth。",
    inconvenience: "名词 n.，不便，不可数。",
    partnership: "名词 n.，合作关系，可数。",
    mutual: "形容词 adj.，共同的、相互的；mutually 是副词。",
  });

  C("slang", [
    { t: "口语省略句", f: "省略主语和谓语的短句", z: "No worries、Fair enough 这类惯用语，整块记住别拆开分析。", e: "No worries." },
    { t: "Let us + 动词原形", f: "Let us + 动词原形", z: "招呼一起做某事；口语里常缩读成 Let us。", e: "Let us call it a day." },
    { t: "have got 口语have", f: "have got + 名词", z: "英式和美式口语里，have got 就等于 have，表示「有」。", e: "I have got your back." },
    { t: "be up to sb", f: "It is up to + 人", z: "表示由某人决定，up to 后面接人或代词宾格。", e: "It is up to you." },
  ], {
    "I am down.": "`be down` 在口语里是「我愿意、算我一个」，和「沮丧」的理解完全不同。",
    "No worries.": "澳洲和英式口语的万能回应，等于没关系、别客气。",
    "To be honest.": "不定式短语作插入语，用来给后面的话加诚实的语气。",
    "Long story short.": "省略了 to make a，表示长话短说，是口语化缩略。",
    "That works for me.": "`work for sb` 表示对某人合适；主语是 that 用第三人称单数 works。",
    "It is up to you.": "`It is up to + 人` 表示由谁决定，up to 后面用宾格。",
    "I feel you.": "口语里 feel 可以表示「理解你的感受」，后面直接跟人。",
    "Fair enough.": "省略句，表示「有道理、可以接受」，语气中性偏认可。",
    "I am beat.": "`be beat` 表示累趴了，注意这里是形容词化的过去分词，不用 beaten。",
    "Let us call it a day.": "`call it a day` 是今天到此为止的习语，it 指这件事。",
    "I am all ears.": "`be all ears` 表示洗耳恭听，ear 要用复数。",
    "Cut to the chase.": "祈使句，`cut to the chase` 表示直入正题。",
    "My bad.": "口语道歉，等于「是我的错」，比 sorry 更随意。",
    "Sort of.": "副词短语，表示「有点、差不多」，语气含糊。",
    "You bet.": "表示当然、没问题，是很地道的答应方式。",
    "Hang in there.": "祈使句，表示坚持住，多用于安慰别人。",
    "Get out of here.": "字面「滚出去」，但在口语里常表示「别开玩笑了」，靠语气分辨。",
    "That is a stretch.": "`a stretch` 表示牵强、夸张，stretch 在这里作名词。",
    "Let it go.": "`let sb/sth go` 表示放手、别纠结；it 放在中间。",
    "I have got your back.": "`have got sb back` 是「支持某人」的习语，back 指后背。",
  }, {
    honest: "形容词 adj.，诚实的；to be honest 说实话。",
    worry: "名词/动词，担心；No worries 没关系。",
    tired: "形容词 adj.，疲倦的；be tired of 厌倦。",
    fair: "形容词 adj.，公平的、合理的；Fair enough 有道理。",
    favor: "名词 n.，帮忙；do me a favor 帮我个忙。",
    chase: "名词/动词，追逐；cut to the chase 直入正题。",
    stretch: "名词/动词，延伸；a stretch 夸张的说法。",
    support: "名词/动词，支持；have sb back 是口语化说法。",
    sort: "名词 n.，种类；sort of 有点。",
    bet: "动词/名词，打赌；You bet 当然。",
  });

  C("beauty", [
    { t: "主谓一致不能丢", f: "名词单复数决定动词形式", z: "读起来像金句，语法上依然是标准主谓一致。", e: "Actions speak louder than words." },
    { t: "比较级 + than", f: "形容词/副词比较级 + than", z: "金句常用比较级表对比，注意 than 不能省。", e: "Actions speak louder than words." },
    { t: "祈使句励志", f: "动词原形开头", z: "Live in the moment 这类句子都是祈使句，省略主语 you。", e: "Live in the moment." },
    { t: "无冠词表达", f: "抽象名词前不加冠词", z: "Time、Silence 等抽象名词泛指时不加 the。", e: "Silence is golden." },
  ], {
    "Every cloud has a silver lining.": "谚语：乌云也有银边，表示困境中总有一线希望；主语单数用 has。",
    "The best is yet to come.": "`be yet to do` 表示尚未发生；best 作名词指最好的事，谓语用 is。",
    "Actions speak louder than words.": "`louder` 是比较级修饰 speak；Actions 是复数主语，用 speak。",
    "Home is where the heart is.": "`where the heart is` 是表语从句；Home 作抽象概念不加冠词。",
    "Time flies.": "`fly` 加 -s 变 flies；这句话用现在时表达普遍真理。",
    "Less is more.": "`less` 与 `more` 都是名词化用法，分别作主语和表语。",
    "Slow and steady wins the race.": "`Slow and steady` 被看作一个整体概念，谓语用单数 wins。",
    "Silence is golden.": "抽象名词 Silence 前不加冠词；golden 是形容词作表语。",
    "Happiness lies in contentment.": "`lie in` 表示在于；`lie` 的第三人称单数形式是 lies。",
    "A journey of a thousand miles begins with a single step.": "`a journey of + 数量` 是「一段……的旅程」；谓语跟随 a journey 用单数 begins。",
    "No pain no gain.": "省略了 there is 的谚语，两个名词并列表示对等关系。",
    "Time and tide wait for no man.": "`Time and tide` 被看作复数，用 wait；`for no man` 表示不等任何人。",
    "Anything is possible.": "不定代词 `Anything` 作主语，谓语用单数 is。",
    "Good things are worth waiting for.": "`be worth + 动词ing` 表示值得做；`wait for` 的介词 for 留在句尾。",
    "Every ending is a new beginning.": "`Every + 单数名词` 用单数谓语 is；ending、beginning 都是动名词化的名词。",
    "Live in the moment.": "祈使句用动词原形开头；`in the moment` 表示活在当下。",
    "Be grateful for what you have.": "祈使句用 be 开头；`be grateful for` 是固定搭配，后面接名词或从句。",
    "Tomorrow is another day.": "抽象时间名词作主语用单数谓语；another 后接单数名词。",
  }, {
    silver: "形容词/名词，银色的；a silver lining 一线希望。",
    journey: "名词 n.，旅程；a journey of 一段……的旅程。",
    silence: "名词 n.，沉默，不可数；in silence 沉默地。",
    contentment: "名词 n.，满足，不可数；形容词是 content。",
    grateful: "形容词 adj.，感激的；be grateful for 对……感激。",
    moment: "名词 n.，时刻；in the moment 当下。",
    beginning: "名词 n.，开始；from the beginning 从头。",
    possible: "形容词 adj.，可能的；as ... as possible 尽可能。",
    patience: "名词 n.，耐心，不可数。",
    tomorrow: "名词/副词，明天；作名词时用单数谓语。",
  });

  C("react", [
    { t: "be + 情绪形容词", f: "be + 形容词 + 介词", z: "情绪表达常用 be 加形容词，再接 for、of、about 等介词。", e: "I am proud of you." },
    { t: "过去分词作形容词", f: "be relieved / excited / disappointed", z: "-ed 结尾的形容词多用来形容人的感受。", e: "I am so relieved." },
    { t: "祈使句安慰", f: "Cheer up / Do not give up", z: "安慰别人时用祈使句，句子短、动词用原形。", e: "Cheer up." },
    { t: "Thank you for doing", f: "Thank you for + 动词ing", z: "感谢对方做过的事，for 后面必须用动名词。", e: "Thank you for always being there." },
  ], {
    "I am so happy for you.": "`be happy for sb` 表示为某人高兴；注意用 for 不用 with。",
    "Cheer up.": "祈使句，`cheer up` 表示振作起来，用于安慰情绪低落的人。",
    "I can relate.": "口语里 `relate` 表示有同感、能理解，本身不与宾语连用。",
    "That is so exciting.": "-ing 形容词描述事情令人兴奋；so 修饰形容词加强语气。",
    "I cannot believe it.": "`cannot + 动词原形`；it 指前面刚提到的事。",
    "What a coincidence.": "感叹句 `What a + 名词`；coincidence 是可数名词，前面必须加 a。",
    "Nice work.": "省略句，完整是 That is nice work；工作类表扬常用。",
    "You did it.": "`did` 是过去式，肯定对方已经做到；口语里重读 did 表示强调。",
    "Do not give up.": "否定祈使句 `do not + 动词原形`；give up 是放弃。",
    "Take your time.": "祈使句固定说法，表示慢慢来、不着急。",
    "I am proud of you.": "`be proud of sb` 为某人骄傲，of 是介词后面跟宾格。",
    "That is disappointing.": "-ing 形容词形容事情令人失望；如果是人失望，要用 disappointed。",
    "I am a little nervous.": "`a little` 修饰形容词表示有点；nervous 形容人的紧张。",
    "I am so relieved.": "`relieved` 是过去分词化的形容词，表示人松了一口气。",
    "That really touched me.": "`touched` 作形容词表示被感动；really 放动词前加强。",
    "Thank you for always being there.": "`Thank you for + 动词ing`；be there for sb 表示一直陪伴。",
    "That is a shame.": "`a shame` 表示遗憾、可惜，不是「羞耻」。",
    "Be careful.": "祈使句用 `Be + 形容词`（不是 carefully），提醒对方小心。",
  }, {
    proud: "形容词 adj.，骄傲的；be proud of 为……骄傲。",
    relieved: "形容词 adj.，宽慰的；be relieved 松一口气。",
    nervous: "形容词 adj.，紧张的；名词是 nervousness。",
    disappointing: "形容词 adj.，令人失望的；修饰人用 disappointed。",
    coincidence: "名词 n.，巧合，可数；What a coincidence 真巧。",
    shame: "名词 n.，遗憾、羞愧；a shame 表示可惜。",
    excite: "动词 v.，使兴奋；形容词 exciting / excited。",
    encourage: "动词 v.，鼓励；encourage sb to do sth。",
    patient: "形容词 adj.，有耐心的；名词是 patience。",
    believe: "动词 v.，相信；believe in 信任。",
  });

  C("smalltalk", [
    { t: "How 开头的寒暄", f: "How are you doing? / How have you been?", z: "问候用进行时表示最近状态，用完成时表示这段时间如何。", e: "How have you been?" },
    { t: "回答用过去时", f: "How was + 名词？", z: "问已经过去的周末、行程，动词要用 was / were。", e: "How was your weekend?" },
    { t: "Would you like ...?", f: "Would you like + 名词 / to do", z: "礼貌邀请，比 Do you want 更得体。", e: "Would you like something to drink?" },
    { t: "现在完成时寒暄", f: "Have you been + 形容词？", z: "问最近状态，用现在完成时表示从过去持续到现在。", e: "Have you been busy lately?" },
  ], {
    "How are you doing?": "现在进行时用于寒暄，等于 How are you；回答 Fine、Good 都可以。",
    "How have you been?": "现在完成时问「这段时间过得怎么样」，适合久未见面的朋友。",
    "It is nice to see you.": "`It is nice to + 动词原形` 是客套句式；初次见面用 meet，重逢用 see。",
    "How was your weekend?": "周末已过去，用过去式 `was`；your 后面跟名词单数。",
    "The weather is nice today.": "天气用 `It is` 或 `The weather is`；`nice` 是万能褒义形容词。",
    "You look great today.": "`look + 形容词` 是系动词用法，表示看起来怎么样，不用 look greatly。",
    "Was the traffic heavy?": "问交通拥堵用 `heavy`，不用 big；疑问句把 Was 提到句首。",
    "Would you like something to drink?": "`Would you like + 名词`；`something to drink` 是不定式作后置定语。",
    "Where are you from?": "问籍贯用 `be from + 地点`；回答 I am from China。",
    "What do you do?": "问职业的固定说法，注意不是问「你在做什么」；用助动词 do 提问。",
    "What are your hobbies?": "hobbies 是可数名词复数；What are 因为主语是复数。",
    "Have you been busy lately?": "现在完成时 + `lately` 问最近状态，这是很地道的寒暄。",
    "I have to get going.": "`have to + 动词原形`；`get going` 是口语「该走了」。",
    "Let us keep in touch.": "`Let us + 动词原形`；keep in touch 是保持联系。",
    "Have a great day.": "祈使句 `Have a + 形容词 + day`，是告别时的祝福。",
    "Talk to you later.": "省略了 I will，表示回头聊，多见于口语和短信。",
  }, {
    weekend: "名词 n.，周末；on the weekend 在周末。",
    weather: "名词 n.，天气，不可数，前面常加 the。",
    traffic: "名词 n.，交通，不可数；heavy traffic 交通拥堵。",
    hometown: "名词 n.，家乡，可数；my hometown 我的家乡。",
    hobbies: "名词 n.，爱好，hobby 的复数，注意 y 变 ies。",
    touch: "名词/动词，联系、触碰；keep in touch 保持联系。",
    drink: "名词/动词，饮料、喝；something to drink 喝的东西。",
    busy: "形容词 adj.，忙碌的；be busy doing sth 忙于做某事。",
  });

})();
